Repository 1-Platform/one-platform, pull requests merged in 2020-05, with the labels that each got.

#228 chore(cli): Added the Dockerfile to cli generator template
  cli/generator-op-microservice/generators/microservice/index.js
  cli/generator-op-microservice/generators/microservice/templates/.dockerignore
  cli/generator-op-microservice/generators/microservice/templates/Dockerfile
Labels: chore

#224 feat(#220) - Creating CRUD for HomeType and MicroserviceDetailsType in the home-service
  packages/home-service/.env.example
  packages/home-service/src/e2e/home.spec.ts
  packages/home-service/src/e2e/mock.json
  packages/home-service/src/resolver.ts
  packages/home-service/src/schema.ts
  packages/home-service/src/typedef.graphql
  packages/home-service/src/types.d.ts
Labels: enhancement

#230 feat(#229) - Backend integration for home-spa and home-service
  packages/home-spa/src/js/controller.js
  packages/home-spa/src/js/service.js
  packages/home-spa/src/mocks/stub.js
  packages/home-spa/src/styles/main.scss
Labels: enhancement

#252 fix(#251) - Home SPA build config removes the SSI include comments from the exported html files
  packages/home-spa/src/contact-us.html
  packages/home-spa/webpack.config.js
Labels: bug

#255 fix(#254) - Add feedback microservice information to the microservice details page
  packages/home-spa/src/js/controller.js
  packages/home-spa/src/mocks/stub.js
Labels: chore

#257 patch(cli): Added nodemon plugin back to the webpack config
  cli/generator-op-microservice/generators/microservice/templates/README.md
  cli/generator-op-microservice/generators/microservice/templates/package.json
  cli/generator-op-microservice/generators/microservice/templates/webpack.common.js
  cli/generator-op-microservice/generators/microservice/templates/webpack.dev.js
  cli/generator-op-microservice/generators/microservice/templates/webpack.prod.js
  packages/api-gateway-service/README.md
  packages/api-gateway-service/package.json
  packages/api-gateway-service/webpack.common.js
  packages/api-gateway-service/webpack.dev.js
  packages/api-gateway-service/webpack.prod.js
  packages/feedback-service/README.md
  packages/feedback-service/package.json
  packages/feedback-service/webpack.common.js
  packages/feedback-service/webpack.dev.js
  packages/feedback-service/webpack.prod.js
  packages/home-service/README.md
  packages/home-service/package.json
  packages/home-service/webpack.common.js
  packages/home-service/webpack.dev.js
  packages/home-service/webpack.prod.js
  packages/user-service/README.md
  packages/user-service/package-lock.json
  packages/user-service/package.json
  packages/user-service/webpack.common.js
  packages/user-service/webpack.dev.js
  packages/user-service/webpack.prod.js
Labels: regression

#262 Unit tests for contact-page, microservice details page and and service getData
  packages/home-spa/src/js/controller.js
  packages/home-spa/src/tests/contact-us.spec.js
  packages/home-spa/src/tests/index.spec.js
  packages/home-spa/src/tests/microservice-details.test.js
Labels: chore

#286 fix/#285 - Lint errors and name fixes, also add owners for home-service
  packages/home-service/src/e2e/home.spec.ts
  packages/home-service/src/e2e/mock.json
  packages/home-service/src/resolver.ts
  packages/home-service/src/schema.ts
  packages/home-service/src/typedef.graphql
  packages/home-service/src/types.d.ts
Labels: chore

#287 fix - 325 Converted the dependent microsevices api host format supported for openshift
  packages/api-gateway-service/.env.example
  packages/api-gateway-service/src/helpers.ts
Labels: dependencies

#281 feat(api): Included support for API query for additional parameters
  packages/user-service/src/e2e/user.spec.ts
  packages/user-service/src/resolver.ts
  packages/user-service/src/typedef.graphql
Labels: chore

#288 fix:332 - Changed the server from https to http mode for all microservices.
  cli/generator-op-microservice/generators/microservice/templates/.env.example
  cli/generator-op-microservice/generators/microservice/templates/gql.service.ts
  cli/generator-op-microservice/generators/microservice/templates/rest.service.ts
  docker-compose.yml
  packages/api-gateway-service/.env.example
  packages/api-gateway-service/service.ts
  packages/feedback-service/.env.example
  packages/feedback-service/service.ts
  packages/home-service/.env.example
  packages/home-service/service.ts
  packages/user-service/.env.example
  packages/user-service/service.ts
Labels: dependencies

#321 fix - 316: Changed the timestamp Object type for user microservice
  packages/user-service/src/cron.ts
  packages/user-service/src/resolver.ts
  packages/user-service/src/schema.ts
  packages/user-service/src/typedef.graphql
  packages/user-service/src/types.d.ts
Labels: dependencies

#320 feat(sso-auth): Implemented the SSO Auth in the header component (SSI)
  .gitignore
  README.md
  docker-compose.yml
  packages/ssi-service/jest.config.js
  packages/ssi-service/package-lock.json
  packages/ssi-service/package.json
  packages/ssi-service/public/index.html
  packages/ssi-service/src/default.html
  packages/ssi-service/src/nav/api.js
  packages/ssi-service/src/nav/auth.js
  packages/ssi-service/src/nav/nav.css
  packages/ssi-service/src/nav/nav.js
  packages/ssi-service/webpack.config.js
Labels: enhancement

#284 fix(#283) - Add the timestamp fields and a owner field to the Home Schema
  packages/home-service/.env.example
  packages/home-service/README.md
  packages/home-service/package.json
  packages/home-service/src/e2e/home.spec.ts
  packages/home-service/src/e2e/mock.json
  packages/home-service/src/helpers.ts
  packages/home-service/src/resolver.ts
  packages/home-service/src/schema.ts
  packages/home-service/src/typedef.graphql
  packages/home-service/src/types.d.ts
Labels: chore
