Repository 1-Platform/one-platform, pull requests merged in 2020-09, with the labels that each got.

#655 fix(ssi): CSS fallbacks for Safari and unsupported broswers
  packages/ssi-service/src/nav/nav.css
Labels: bug

#658 feat(#55) - Pull native git config to the cli
  cli/generator-op-microservice/generators/microservice/index.js
Labels: enhancement

#685 chore(ssi): Minor css changes for SSI and User profile url fix
  packages/ssi-service/src/nav/nav.css
  packages/ssi-service/src/nav/nav.js
Labels: chore

#684 fix(user-group-spa): Minor hotfixes and spaship init
  packages/user-group-spa/spaship.yaml
  packages/user-group-spa/src/App.jsx
  packages/user-group-spa/src/components/Form.jsx
  packages/user-group-spa/src/components/User.jsx
  packages/user-group-spa/src/services/GroupsAPI.js
Labels: bug

#688 fix-687: Updated microservices with fix as resulted from the upgrade on webpack
  cli/generator-op-microservice/generators/microservice/templates/webpack.dev.js
  cli/generator-op-microservice/generators/microservice/templates/webpack.prod.js
  packages/api-gateway-service/webpack.dev.js
  packages/api-gateway-service/webpack.prod.js
  packages/feedback-service/webpack.dev.js
  packages/feedback-service/webpack.prod.js
  packages/home-service/webpack.dev.js
  packages/home-service/webpack.prod.js
  packages/notifications-service/webpack.dev.js
  packages/notifications-service/webpack.prod.js
  packages/search-service/webpack.dev.js
  packages/search-service/webpack.prod.js
  packages/user-group-service/webpack.dev.js
  packages/user-group-service/webpack.prod.js
Labels: bug

#689 fix(user-groups-spa): Fixed useState looping in some edge cases
  packages/user-group-spa/src/App.jsx
  packages/user-group-spa/src/components/Home.jsx
Labels: bug

#691 chore(#690): Setup Code Scanning
  .github/workflows/codeql-analysis.yml
Labels: chore, enhancement

#687 hotfix(ssi): Changed post-auth redirect to use replaceState
  packages/ssi-service/src/auth.js
Labels: bug

#703 fix-253 - Included Handover tool in API gateway
  packages/api-gateway-service/.env.example
  packages/api-gateway-service/service.ts
Labels: dependencies

#702 feat:580 Included documentation for the Handover SPA
  packages/documentation-spa/docs/apps/hosted/mod-handovers/create-edit.png
  packages/documentation-spa/docs/apps/hosted/mod-handovers/details.png
  packages/documentation-spa/docs/apps/hosted/mod-handovers/home.png
  packages/documentation-spa/docs/apps/hosted/mod-handovers/mod-handover-spa.md
  packages/documentation-spa/sidebars.js
Labels: documentation

#705 feat(user-group-spa): Added opc-header to the User Group SPA
  packages/user-group-spa/package-lock.json
  packages/user-group-spa/package.json
  packages/user-group-spa/src/App.jsx
  packages/user-group-spa/src/components/Form.jsx
  packages/user-group-spa/src/components/Group.jsx
  packages/user-group-spa/src/components/Home.jsx
  packages/user-group-spa/src/components/NotFound.jsx
  packages/user-group-spa/src/components/User.jsx
  packages/user-group-spa/src/context/BreadcrumbContext.jsx
  packages/user-group-spa/src/index.js
Labels: enhancement

#706 feat(search): included solr endpoint support for search
  packages/search-service/.env.example
  packages/search-service/src/helpers.ts
  packages/search-service/src/resolver.ts
  packages/search-service/src/typedef.graphql
  packages/search-service/src/types.d.ts
  packages/search-spa/src/app/app.gql.ts
  packages/search-spa/src/app/search/search.component.html
  packages/search-spa/src/app/search/search.component.scss
  packages/search-spa/src/app/search/search.component.ts
  packages/search-spa/src/app/types.d.ts
Labels: dependencies

#697 fix(#659) - Add header & footer to home, notification and feedback SPA
  packages/common/footer.json
  packages/feedback-spa/package-lock.json
  packages/feedback-spa/package.json
  packages/feedback-spa/src/app/app.component.html
  packages/feedback-spa/src/app/app.component.spec.ts
  packages/feedback-spa/src/app/app.component.ts
  packages/feedback-spa/src/app/app.module.ts
  packages/feedback-spa/src/app/feedback/feedback.fragment.ts
  packages/feedback-spa/src/app/feedback/feedback.gql.ts
  packages/feedback-spa/src/app/graphql.module.ts
  packages/feedback-spa/src/app/module.d.ts
  packages/feedback-spa/src/index.html
  packages/feedback-spa/tsconfig.app.json
  packages/feedback-spa/tsconfig.spec.json
  packages/home-spa/package-lock.json
  packages/home-spa/package.json
  packages/home-spa/src/app.js
  packages/home-spa/src/img/end-quote.svg
  packages/home-spa/src/js/controller.js
  packages/home-spa/src/styles/common.scss
  packages/home-spa/src/styles/main.scss
  packages/home-spa/webpack.config.js
  packages/notification-spa/package-lock.json
  packages/notification-spa/package.json
  packages/notification-spa/src/app/app.component.html
  packages/notification-spa/src/app/app.component.scss
  packages/notification-spa/src/app/app.component.spec.ts
  packages/notification-spa/src/app/app.component.ts
  packages/notification-spa/src/app/app.gql.ts
  packages/notification-spa/src/app/app.module.ts
  packages/notification-spa/src/app/graphql.module.ts
  packages/notification-spa/src/app/header/header.component.html
  packages/notification-spa/src/app/header/header.component.scss
  packages/notification-spa/src/app/header/header.component.spec.ts
  packages/notification-spa/src/app/header/header.component.ts
  packages/notification-spa/src/app/manage-notification/manage-notification.component.html
  packages/notification-spa/src/app/side-panel/side-panel.component.scss
  packages/notification-spa/tsconfig.app.json
  packages/notification-spa/tsconfig.spec.json
  packages/user-profile-spa/package-lock.json
  packages/user-profile-spa/package.json
  packages/user-profile-spa/src/app/app.component.html
  packages/user-profile-spa/src/app/app.component.ts
  packages/user-profile-spa/src/app/app.module.ts
  packages/user-profile-spa/src/app/user-profile-components/header/header.component.html
  packages/user-profile-spa/src/app/user-profile-components/header/header.component.scss
  packages/user-profile-spa/src/app/user-profile-components/header/header.component.spec.ts
  packages/user-profile-spa/src/app/user-profile-components/header/header.component.ts
Labels: chore

#724 fix:721 - Removed the borders in search listing
  packages/search-spa/src/app/search/search.component.html
  packages/search-spa/src/app/search/search.component.scss
Labels: chore
