Repository 1-Platform/one-platform, pull requests merged in 2020-04, with the labels that each got.

#118 feat(ldap-microservice): REST based ldap microservice which enables to talk to LDAP
  packages/ldap-integration/.env.example
  packages/ldap-integration/.gitignore
  packages/ldap-integration/README.md
  packages/ldap-integration/jest.config.js
  packages/ldap-integration/package-lock.json
  packages/ldap-integration/package.json
  packages/ldap-integration/service.ts
  packages/ldap-integration/src/api.ts
  packages/ldap-integration/src/e2e/ldap.spec.ts
  packages/ldap-integration/src/e2e/mock.json
  packages/ldap-integration/src/helpers.ts
  packages/ldap-integration/src/schema.ts
  packages/ldap-integration/src/types.d.ts
  packages/ldap-integration/tsconfig.json
  packages/ldap-integration/tslint.json
  packages/ldap-integration/webpack.common.js
  packages/ldap-integration/webpack.dev.js
  packages/ldap-integration/webpack.prod.js
Labels: enhancement

#107 feat(feedback-spa) - List all the feedback in listing page
  packages/feedback-spa/.editorconfig
  packages/feedback-spa/.gitignore
  packages/feedback-spa/README.md
  packages/feedback-spa/angular.json
  packages/feedback-spa/browserslist
  packages/feedback-spa/e2e/protractor.conf.js
  packages/feedback-spa/e2e/src/app.e2e-spec.ts
  packages/feedback-spa/e2e/src/app.po.ts
  packages/feedback-spa/e2e/tsconfig.json
  packages/feedback-spa/package-lock.json
  packages/feedback-spa/package.json
  packages/feedback-spa/src/app/apollo.config.ts
  packages/feedback-spa/src/app/app-routing.module.ts
  packages/feedback-spa/src/app/app.component.html
  packages/feedback-spa/src/app/app.component.spec.ts
  packages/feedback-spa/src/app/app.component.ts
  packages/feedback-spa/src/app/app.module.ts
  packages/feedback-spa/src/app/app.service.ts
  packages/feedback-spa/src/app/modules/feedback/feedback-item/feedback-item.component.html
  packages/feedback-spa/src/app/modules/feedback/feedback-item/feedback-item.component.scss
  packages/feedback-spa/src/app/modules/feedback/feedback-item/feedback-item.component.spec.ts
  packages/feedback-spa/src/app/modules/feedback/feedback-item/feedback-item.component.ts
  packages/feedback-spa/src/app/modules/feedback/feedback.fragment.ts
  packages/feedback-spa/src/app/modules/feedback/feedback.gql.ts
  packages/feedback-spa/src/app/modules/feedback/feedback.service.ts
  packages/feedback-spa/src/app/modules/feedback/feedback.ts
  packages/feedback-spa/src/app/modules/feedback/home/feedback-home.component.html
  packages/feedback-spa/src/app/modules/feedback/home/feedback-home.component.scss
  packages/feedback-spa/src/app/modules/feedback/home/feedback-home.component.spec.ts
  packages/feedback-spa/src/app/modules/feedback/home/feedback-home.component.ts
  packages/feedback-spa/src/app/modules/feedback/jest.config.js
  packages/feedback-spa/src/app/modules/feedback/testing/mocks/feedback.mock.ts
  packages/feedback-spa/src/assets/.gitkeep
  packages/feedback-spa/src/environments/environment.dev.ts
  packages/feedback-spa/src/environments/environment.prod.ts
  packages/feedback-spa/src/environments/environment.qa.ts
  packages/feedback-spa/src/environments/environment.stage.ts
  packages/feedback-spa/src/environments/environment.ts
  packages/feedback-spa/src/favicon.ico
  packages/feedback-spa/src/index.html
  packages/feedback-spa/src/jestGlobalMocks.ts
  packages/feedback-spa/src/main.ts
  packages/feedback-spa/src/polyfills.ts
  packages/feedback-spa/src/scss/colors/_colors.scss
  packages/feedback-spa/src/scss/component/_component.scss
  packages/feedback-spa/src/scss/mixin/_mixin.scss
  packages/feedback-spa/src/setupJest.ts
  packages/feedback-spa/src/styles.scss
  packages/feedback-spa/src/test.ts
  packages/feedback-spa/tsconfig.app.json
  packages/feedback-spa/tsconfig.json
  packages/feedback-spa/tsconfig.spec.json
  packages/feedback-spa/tslint.json
Labels: enhancement

#144 feat(user-group microservice) - User Group microservice with ldap integration with sync jobs
  packages/ldap-integration/README.md
  packages/ldap-integration/package.json
  packages/ldap-integration/service.ts
  packages/ldap-integration/src/api.ts
  packages/ldap-integration/src/e2e/ldap.spec.ts
  packages/ldap-integration/src/e2e/mock.json
  packages/ldap-integration/src/schema.ts
  packages/user-service/.env.example
  packages/user-service/.gitignore
  packages/user-service/README.md
  packages/user-service/jest.config.js
  packages/user-service/package-lock.json
  packages/user-service/package.json
  packages/user-service/service.ts
  packages/user-service/src/cron.ts
  packages/user-service/src/e2e/mock.json
  packages/user-service/src/e2e/user.spec.ts
  packages/user-service/src/helpers.ts
  packages/user-service/src/resolver.ts
  packages/user-service/src/schema.ts
  packages/user-service/src/typedef.graphql
  packages/user-service/src/types.d.ts
  packages/user-service/tsconfig.json
  packages/user-service/tslint.json
  packages/user-service/webpack.common.js
  packages/user-service/webpack.dev.js
  packages/user-service/webpack.prod.js
Labels: enhancement

#149 chore(#148): Implemented VScode workspace configuration.
  .gitignore
  .vscode/settings.json
  one-platform.code-workspace
Labels: chore

#151 fix(#150): Fixed npm audit vulnerabilities.
  package-lock.json
Labels: bug, chore

#152 fix(#150): Fixed npm audit vulnerabilities across packages.
  cli/generator-op-microservice/package-lock.json
  packages/home-spa/package-lock.json
  packages/ssi-service/package-lock.json
  packages/user-service/package-lock.json
Labels: bug, chore

#154 fix(#153): Fixed all markdown lint issues.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/chore.md
  .github/ISSUE_TEMPLATE/documentation_proposal.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/regression_report.md
  .github/PULL_REQUEST_TEMPLATE.md
  .vscode/settings.json
  CODE_OF_CONDUCT.md
  README.md
  cli/generator-op-microservice/README.md
  cli/generator-op-microservice/generators/microservice/templates/README.md
  packages/feedback-spa/README.md
  packages/home-spa/README.md
  packages/ssi-service/README.md
Labels: bug, chore, documentation

#197 feat(#196) - Remove the tabs from home page and change to linear structure
  packages/home-spa/src/index.html
  packages/home-spa/src/js/controller.js
  packages/home-spa/src/styles/common.scss
  packages/home-spa/src/styles/main.scss
  packages/home-spa/src/tests/index.spec.js
Labels: chore, enhancement

#201 feat(#200) - Microservice details page in home-spa
  packages/home-spa/src/404.html
  packages/home-spa/src/img/Auth-illustration.svg
  packages/home-spa/src/img/Feedback-illustration.svg
  packages/home-spa/src/img/Notification-illustration.svg
  packages/home-spa/src/img/Search-illustration.svg
  packages/home-spa/src/img/User-profile-illustration.svg
  packages/home-spa/src/index.html
  packages/home-spa/src/js/controller.js
  packages/home-spa/src/microservice-details.html
  packages/home-spa/src/mocks/stub.js
  packages/home-spa/src/styles/common.scss
  packages/home-spa/src/styles/main.scss
  packages/home-spa/src/tests/404.spec.js
  packages/home-spa/webpack.config.js
Labels: enhancement

#146 feat(#130) - A notification framework management SPA to set configuration for SPA owners and users
  packages/notification-spa/.editorconfig
  packages/notification-spa/.gitignore
  packages/notification-spa/README.md
  packages/notification-spa/angular.json
  packages/notification-spa/browserslist
  packages/notification-spa/e2e/protractor.conf.js
  packages/notification-spa/e2e/src/app.e2e-spec.ts
  packages/notification-spa/e2e/src/app.po.ts
  packages/notification-spa/e2e/tsconfig.json
  packages/notification-spa/jest.config.js
  packages/notification-spa/package-lock.json
  packages/notification-spa/package.json
  packages/notification-spa/src/app/app-routing.module.ts
  packages/notification-spa/src/app/app.component.html
  packages/notification-spa/src/app/app.component.scss
  packages/notification-spa/src/app/app.component.spec.ts
  packages/notification-spa/src/app/app.component.ts
  packages/notification-spa/src/app/app.gql.ts
  packages/notification-spa/src/app/app.module.ts
  packages/notification-spa/src/app/app.service.spec.ts
  packages/notification-spa/src/app/app.service.ts
  packages/notification-spa/src/app/graphql.module.ts
  packages/notification-spa/src/app/header/header.component.html
  packages/notification-spa/src/app/header/header.component.scss
  packages/notification-spa/src/app/header/header.component.spec.ts
  packages/notification-spa/src/app/header/header.component.ts
  packages/notification-spa/src/app/helper.ts
  packages/notification-spa/src/app/index/index.component.html
  packages/notification-spa/src/app/index/index.component.scss
  packages/notification-spa/src/app/index/index.component.spec.ts
  packages/notification-spa/src/app/index/index.component.ts
  packages/notification-spa/src/app/index/spa-notifications-list/spa-notifications-list.component.html
  packages/notification-spa/src/app/index/spa-notifications-list/spa-notifications-list.component.scss
  packages/notification-spa/src/app/index/spa-notifications-list/spa-notifications-list.component.ts
  packages/notification-spa/src/app/manage-notification/manage-notification.component.html
  packages/notification-spa/src/app/manage-notification/manage-notification.component.scss
  packages/notification-spa/src/app/manage-notification/manage-notification.component.spec.ts
  packages/notification-spa/src/app/manage-notification/manage-notification.component.ts
  packages/notification-spa/src/app/manage-notification/type.d.ts
  packages/notification-spa/src/app/mocks/notificationItems.mock.ts
  packages/notification-spa/src/app/mocks/user.mock.ts
  packages/notification-spa/src/app/side-panel/side-panel.component.html
  packages/notification-spa/src/app/side-panel/side-panel.component.scss
  packages/notification-spa/src/app/side-panel/side-panel.component.spec.ts
  packages/notification-spa/src/app/side-panel/side-panel.component.ts
  packages/notification-spa/src/assets/.gitkeep
  packages/notification-spa/src/environments/environment.prod.ts
  packages/notification-spa/src/environments/environment.ts
  packages/notification-spa/src/favicon.ico
  packages/notification-spa/src/index.html
  packages/notification-spa/src/main.ts
  packages/notification-spa/src/polyfills.ts
  packages/notification-spa/src/setup-jest.ts
  packages/notification-spa/src/styles.scss
  packages/notification-spa/src/test-config.helper.ts
  packages/notification-spa/tsconfig.app.json
  packages/notification-spa/tsconfig.json
  packages/notification-spa/tsconfig.spec.json
  packages/notification-spa/tslint.json
Labels: chore, enhancement

#218 feat(#217) - Backend & DB for Home page - Creating basic dir structure and using the CLI generator and adding types
  packages/home-service/.env.example
  packages/home-service/.gitignore
  packages/home-service/README.md
  packages/home-service/jest.config.js
  packages/home-service/package-lock.json
  packages/home-service/package.json
  packages/home-service/service.ts
  packages/home-service/src/e2e/home.spec.ts
  packages/home-service/src/e2e/mock.json
  packages/home-service/src/helpers.ts
  packages/home-service/src/resolver.ts
  packages/home-service/src/schema.ts
  packages/home-service/src/typedef.graphql
  packages/home-service/src/types.d.ts
  packages/home-service/tsconfig.json
  packages/home-service/tslint.json
  packages/home-service/webpack.common.js
  packages/home-service/webpack.dev.js
  packages/home-service/webpack.prod.js
Labels: enhancement

#223 fix(#222): Added LDAP reconnection param to the ldap
  packages/user-service/src/helpers.ts
Labels: chore

#221 chore(ssi-service): Code cleanup for the SSI template file and implemented dotenv
  packages/ssi-service/.env.example
  packages/ssi-service/.gitignore
  packages/ssi-service/package-lock.json
  packages/ssi-service/package.json
  packages/ssi-service/public/index.html
  packages/ssi-service/src/default.html
  packages/ssi-service/src/feedback-panel/feedback.js
  packages/ssi-service/webpack.config.js
Labels: chore

#227 feat/docker-setup: Dockerfiles and docker-compose setup for all SPAs and Microservices
  cli/generator-op-microservice/generators/microservice/templates/webpack.common.js
  docker-compose.yml
  packages/api-gateway-service/.dockerignore
  packages/api-gateway-service/Dockerfile
  packages/api-gateway-service/webpack.common.js
  packages/feedback-service/.dockerignore
  packages/feedback-service/Dockerfile
  packages/feedback-service/webpack.common.js
  packages/feedback-spa/.dockerignore
  packages/feedback-spa/Dockerfile
  packages/home-service/.dockerignore
  packages/home-service/Dockerfile
  packages/home-service/webpack.common.js
  packages/home-spa/.dockerignore
  packages/home-spa/Dockerfile
  packages/notification-spa/.dockerignore
  packages/notification-spa/Dockerfile
  packages/ssi-service/Dockerfile
  packages/ssi-service/httpd.conf
  packages/user-service/.dockerignore
  packages/user-service/Dockerfile
  packages/user-service/webpack.common.js
Labels: enhancement

#226 feat(#225) - Contact us page for home-spa
  packages/home-spa/package-lock.json
  packages/home-spa/src/404.html
  packages/home-spa/src/app.js
  packages/home-spa/src/contact-us.html
  packages/home-spa/src/img/co-working.svg
  packages/home-spa/src/img/user-female.svg
  packages/home-spa/src/img/user-male.svg
  packages/home-spa/src/index.html
  packages/home-spa/src/js/controller.js
  packages/home-spa/src/mocks/stub.js
  packages/home-spa/src/styles/common.scss
  packages/home-spa/src/styles/main.scss
  packages/home-spa/webpack.config.js
Labels: enhancement
