Repository 1-Platform/one-platform, pull requests merged in 2020-02, with the labels that each got.

#23 SSI Templates for Header and Feedback form
  .eslintrc.json
  .vscode/extensions.json
  .vscode/settings.json
  docker-compose.yml
  packages/ssi-service/.dockerignore
  packages/ssi-service/.gitignore
  packages/ssi-service/Dockerfile
  packages/ssi-service/README.md
  packages/ssi-service/httpd.conf
  packages/ssi-service/jest.config.js
  packages/ssi-service/package-lock.json
  packages/ssi-service/package.json
  packages/ssi-service/public/index.html
  packages/ssi-service/src/assets/rh-op-logo.svg
  packages/ssi-service/src/default.ssi
  packages/ssi-service/src/feedback-panel/feedback.css
  packages/ssi-service/src/feedback-panel/feedback.js
  packages/ssi-service/src/feedback-panel/secrets.example.json
  packages/ssi-service/src/nav/nav.css
  packages/ssi-service/src/nav/nav.js
  packages/ssi-service/tests/feedback-panel.spec.js
  packages/ssi-service/tests/nav.spec.js
  packages/ssi-service/webpack.config.js
Labels: enhancement

#32 chore(#31): Add Contributors Code of Conduct
  CODE_OF_CONDUCT.md
Labels: chore, documentation

#24 chore(github): Update the PR template with issue linking keywords
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#28 docs(#27) - Adding readme to One Platform
  README.md
Labels: documentation
