Repository 1-Platform/one-platform, pull requests merged in 2020-03, with the labels that each got.

#22 feat(#19) - A landing page(home-spa) for One-Platform
  packages/common/_colors.scss
  packages/home-spa/.gitignore
  packages/home-spa/README.md
  packages/home-spa/jest.config.js
  packages/home-spa/package-lock.json
  packages/home-spa/package.json
  packages/home-spa/src/404.html
  packages/home-spa/src/app.js
  packages/home-spa/src/img/404.svg
  packages/home-spa/src/img/Red Hat Logo.svg
  packages/home-spa/src/img/bell.svg
  packages/home-spa/src/img/illustration.svg
  packages/home-spa/src/img/login.svg
  packages/home-spa/src/img/magnifying-glass.svg
  packages/home-spa/src/img/padlock.svg
  packages/home-spa/src/img/shield.svg
  packages/home-spa/src/img/talk-bubble.svg
  packages/home-spa/src/index.html
  packages/home-spa/src/js/controller.js
  packages/home-spa/src/js/service.js
  packages/home-spa/src/js/vendor/lib
  packages/home-spa/src/styles/_colors.scss
  packages/home-spa/src/styles/_mixin.scss
  packages/home-spa/src/styles/common.scss
  packages/home-spa/src/styles/main.scss
  packages/home-spa/src/tests/404.spec.js
  packages/home-spa/src/tests/index.spec.js
  packages/home-spa/webpack.dev.js
  packages/home-spa/webpack.prod.js
Labels: enhancement

#44 feat(cli): yeoman generator for one platform microservice with graphql and rest support
  .editorconfig
  cli-init.sh
  cli/generator-op-microservice/.eslintignore
  cli/generator-op-microservice/.gitattributes
  cli/generator-op-microservice/.gitignore
  cli/generator-op-microservice/.yo-rc.json
  cli/generator-op-microservice/README.md
  cli/generator-op-microservice/__tests__/app.js
  cli/generator-op-microservice/generators/microservice/index.js
  cli/generator-op-microservice/generators/microservice/templates/.env.example
  cli/generator-op-microservice/generators/microservice/templates/.gitignore
  cli/generator-op-microservice/generators/microservice/templates/README.md
  cli/generator-op-microservice/generators/microservice/templates/gql.service.ts
  cli/generator-op-microservice/generators/microservice/templates/jest.config.js
  cli/generator-op-microservice/generators/microservice/templates/package.json
  cli/generator-op-microservice/generators/microservice/templates/rest.service.ts
  cli/generator-op-microservice/generators/microservice/templates/scripts/postinstall.js
  cli/generator-op-microservice/generators/microservice/templates/src/api.ts
  cli/generator-op-microservice/generators/microservice/templates/src/e2e/.test.env.example
  cli/generator-op-microservice/generators/microservice/templates/src/e2e/gql.service.spec.ts
  cli/generator-op-microservice/generators/microservice/templates/src/e2e/mock.json
  cli/generator-op-microservice/generators/microservice/templates/src/e2e/rest.service.spec.ts
  cli/generator-op-microservice/generators/microservice/templates/src/helpers.ts
  cli/generator-op-microservice/generators/microservice/templates/src/resolver.ts
  cli/generator-op-microservice/generators/microservice/templates/src/schema.ts
  cli/generator-op-microservice/generators/microservice/templates/src/typedef.graphql
  cli/generator-op-microservice/generators/microservice/templates/src/types.d.ts
  cli/generator-op-microservice/generators/microservice/templates/tsconfig.json
  cli/generator-op-microservice/generators/microservice/templates/tslint.json
  cli/generator-op-microservice/generators/microservice/templates/webpack.common.js
  cli/generator-op-microservice/generators/microservice/templates/webpack.dev.js
  cli/generator-op-microservice/generators/microservice/templates/webpack.prod.js
  cli/generator-op-microservice/package-lock.json
  cli/generator-op-microservice/package.json
  package.json
Labels: cli

#110 fix(#109): Changes required in the home-spa code as the dependencies need to be upgraded
  packages/home-spa/package-lock.json
  packages/home-spa/package.json
  packages/home-spa/src/404.html
  packages/home-spa/src/index.html
  packages/home-spa/webpack.dev.js
  packages/home-spa/webpack.prod.js
Labels: bug, dependencies

#127 fix(#125) - Add API to home-spa and use .env file to store the URL
  packages/home-spa/.env.example
  packages/home-spa/.gitignore
  packages/home-spa/README.md
  packages/home-spa/package-lock.json
  packages/home-spa/package.json
  packages/home-spa/src/index.html
  packages/home-spa/src/js/controller.js
  packages/home-spa/src/js/service.js
  packages/home-spa/src/mocks/stub.js
  packages/home-spa/src/styles/common.scss
  packages/home-spa/src/styles/main.scss
  packages/home-spa/src/tests/index.spec.js
  packages/home-spa/webpack.config.js
  packages/home-spa/webpack.dev.js
Labels: chore, enhancement

#129 chore(deps): Updated renovate config
  renovate.json
Labels: chore, dependencies
