Repository 1-Platform/one-platform, pull requests merged in 2020-10, with the labels that each got.

#726 fix:(#4902) - Fixed the interpolation of timestamp in the search ui
  packages/search-spa/src/app/search/search.component.html
Labels: bug

#727 feat(api-gateway): Added dynamic config for API Gateway
  docker-compose.yml
  packages/api-gateway-service/.env.example
  packages/api-gateway-service/README.md
  packages/api-gateway-service/config.json
  packages/api-gateway-service/package-lock.json
  packages/api-gateway-service/package.json
  packages/api-gateway-service/service.ts
  packages/api-gateway-service/src/schema.ts
  packages/api-gateway-service/webpack.common.js
Labels: enhancement

#728 fix(#718) - Installation documentation for using One Platform
  README.md
  package.json
  platform.js
Labels: documentation

#733 fix(#732) - Citation (quotes) position needs to be fixed on the home page for firefox
  packages/home-spa/src/styles/main.scss
Labels: bug

#734 feat(api-gateway): Implemented API Key auth for the API Gateway
  packages/api-gateway-service/package-lock.json
  packages/api-gateway-service/package.json
  packages/api-gateway-service/service.ts
  packages/api-gateway-service/src/helpers.ts
  packages/api-gateway-service/src/schema.ts
  packages/user-group-service/package-lock.json
  packages/user-group-service/package.json
  packages/user-group-service/service.ts
  packages/user-group-service/src/api-keys/resolver.ts
  packages/user-group-service/src/api-keys/schema.ts
  packages/user-group-service/src/api-keys/typedef.graphql
  packages/user-group-service/src/api-keys/util.ts
  packages/user-group-service/src/types.d.ts
  packages/user-group-service/tsconfig.json
Labels: enhancement

#747 enhancement(sso): Changed the SSO auth flow to standard flow
  packages/ssi-service/src/auth.js
  packages/ssi-service/src/default.html
Labels: enhancement

#750 fix:770 - Microservice build failing due to missing typescript package
  cli/generator-op-microservice/generators/microservice/templates/package.json
  packages/api-gateway-service/package-lock.json
  packages/feedback-service/package-lock.json
  packages/feedback-service/package.json
  packages/home-service/package-lock.json
  packages/home-service/package.json
  packages/notifications-service/package-lock.json
  packages/notifications-service/package.json
  packages/search-service/package-lock.json
  packages/search-service/package.json
  packages/user-group-service/package-lock.json
Labels: bug

#746 (fix:551) - Included support for token in search implementation
  packages/search-service/.env.example
  packages/search-service/src/helpers.ts
  packages/search-service/src/typedef.graphql
  packages/search-spa/src/app/app.gql.ts
  packages/search-spa/src/app/types.d.ts
Labels: chore

#759 fix:682 - Fixed the Logout functionality issue to the header menu options
  packages/ssi-service/package.json
  packages/ssi-service/src/nav/nav.js
Labels: bug

#751 fix(ssi): SSI cleanup and style-loader fix
  packages/ssi-service/package-lock.json
  packages/ssi-service/package.json
  packages/ssi-service/public/index.html
  packages/ssi-service/src/auth.js
  packages/ssi-service/src/default.html
  packages/ssi-service/src/feedback-panel/feedback.js
  packages/ssi-service/src/nav/nav.css
  packages/ssi-service/src/nav/nav.js
  packages/ssi-service/webpack.config.js
Labels: enhancement

#749 fix(api-gateway): Changed the .env config setup in the microservices
  packages/api-gateway-service/.env.example
  packages/api-gateway-service/config.json
  packages/api-gateway-service/package-lock.json
  packages/api-gateway-service/package.json
  packages/api-gateway-service/service.ts
  packages/api-gateway-service/src/helpers.ts
  packages/api-gateway-service/src/schema.ts
  packages/api-gateway-service/webpack.common.js
  packages/feedback-service/.env.example
  packages/feedback-service/package-lock.json
  packages/feedback-service/package.json
  packages/feedback-service/service.ts
  packages/feedback-service/webpack.common.js
  packages/home-service/.env.example
  packages/home-service/package-lock.json
  packages/home-service/package.json
  packages/home-service/service.ts
  packages/home-service/webpack.common.js
  packages/notifications-service/.env.example
  packages/notifications-service/package-lock.json
  packages/notifications-service/package.json
  packages/notifications-service/service.ts
  packages/notifications-service/src/broadcaster.ts
  packages/notifications-service/webpack.common.js
  packages/search-service/.env.example
  packages/search-service/package-lock.json
  packages/search-service/package.json
  packages/search-service/service.ts
  packages/search-service/webpack.common.js
  packages/user-group-service/.env.example
  packages/user-group-service/package-lock.json
  packages/user-group-service/package.json
  packages/user-group-service/service.ts
  packages/user-group-service/src/helpers.ts
  packages/user-group-service/webpack.common.js
Labels: bug, enhancement

#761 fix:789 - Apollo Client configuration has updated with the changes on apollo-client
  packages/search-spa/package-lock.json
  packages/search-spa/package.json
  packages/search-spa/src/app/graphql.module.ts
Labels: bug

#773 fix(#772) - Add a public path to home-spa build config
  packages/home-spa/webpack.config.js
Labels: chore
