Repository 1-Platform/one-platform, pull requests merged in 2020-06, with the labels that each got.

#368 Use .lean() in home-service
  packages/home-service/src/helpers.ts
  packages/home-service/src/resolver.ts
Labels: chore

#375 fix(#374) - Add base_url for notification SPA
  packages/notification-spa/package-lock.json
  packages/notification-spa/package.json
  packages/notification-spa/src/app/helper.ts
  packages/notification-spa/src/index.html
Labels: bug

#402 fix(ssi-templates): SSI template hotfixes for firefox and spaship
  docker-compose.yml
  packages/ssi-service/.npmignore
  packages/ssi-service/Dockerfile
  packages/ssi-service/package-lock.json
  packages/ssi-service/src/feedback-panel/feedback.js
  packages/ssi-service/src/nav/auth.js
  packages/ssi-service/src/nav/nav.js
  packages/ssi-service/tests/setupJest.js
Labels: enhancement

#369 feat: 362, 371 Added subscription support to the gateway with schema stiching
  cli/generator-op-microservice/generators/microservice/templates/gql.service.ts
  cli/generator-op-microservice/generators/microservice/templates/package.json
  packages/api-gateway-service/.env.example
  packages/api-gateway-service/package.json
  packages/api-gateway-service/service.ts
  packages/api-gateway-service/src/helpers.ts
  packages/feedback-service/package-lock.json
  packages/feedback-service/package.json
  packages/feedback-service/service.ts
  packages/feedback-service/src/helpers.ts
  packages/home-service/package-lock.json
  packages/home-service/package.json
  packages/home-service/service.ts
  packages/home-service/src/helpers.ts
  packages/user-service/package-lock.json
  packages/user-service/package.json
  packages/user-service/service.ts
  packages/user-service/src/helpers.ts
Labels: cli, enhancement

#404 feat(#403) - Flag to check if spa/microservice is enabled or disabled
  packages/home-service/README.md
  packages/home-service/src/e2e/home.spec.ts
  packages/home-service/src/e2e/mock.json
  packages/home-service/src/schema.ts
  packages/home-service/src/typedef.graphql
  packages/home-service/src/types.d.ts
Labels: enhancement

#364 fix(#362) - Home Page Design Improvements
  packages/home-spa/package.json
  packages/home-spa/src/app.js
  packages/home-spa/src/index.html
  packages/home-spa/src/js/controller.js
  packages/home-spa/src/mocks/stub.js
  packages/home-spa/src/styles/main.scss
Labels: chore

#414 fix(#413) - Remove non-nullable from home-service
  packages/home-service/package-lock.json
  packages/home-service/src/typedef.graphql
Labels: bug

#412 fix(#410) - Home-SPA should be able to fetch information form the API gateway
  packages/home-spa/src/js/service.js
Labels: bug, chore

#440 fix(#391) - Included the error handling with the server and added retry options
  packages/api-gateway-service/package-lock.json
  packages/api-gateway-service/package.json
  packages/api-gateway-service/service.ts
  packages/api-gateway-service/src/helpers.ts
Labels: bug

#420 feat(#419) - Create getHomeTypeByUser API endpoint in home-service
  packages/home-service/src/resolver.ts
  packages/home-service/src/typedef.graphql
Labels: enhancement

#442 feat(notifications-service): Implemented the Notifications Rule engine
  docker-compose.yml
  packages/api-gateway-service/.env.example
  packages/feedback-service/.env.example
  packages/home-service/.env.example
  packages/notifications-service/.env.example
  packages/notifications-service/package-lock.json
  packages/notifications-service/package.json
  packages/notifications-service/service.ts
  packages/notifications-service/src/__mocks__/mockData.json
  packages/notifications-service/src/__tests__/notificationConfig.spec.ts
  packages/notifications-service/src/broadcaster.ts
  packages/notifications-service/src/engine.ts
  packages/notifications-service/src/helpers.ts
  packages/notifications-service/src/notificationConfig/resolver.ts
  packages/notifications-service/src/notificationConfig/schema.ts
  packages/notifications-service/src/notificationConfig/typedef.graphql
  packages/notifications-service/src/resolver.ts
  packages/notifications-service/src/schema.ts
  packages/notifications-service/src/typedef.graphql
  packages/notifications-service/src/types.d.ts
  packages/user-service/.env.example
Labels: enhancement

#411 feat(#405) - Show One Portal Apps (grayed out) in Apps menu - SSI
  packages/ssi-service/src/nav/api.js
  packages/ssi-service/src/nav/nav.css
  packages/ssi-service/src/nav/nav.js
Labels: enhancement

#444 fix:371 Updated the Cors options to default
  packages/api-gateway-service/service.ts
Labels: bug

#447 fix(397)-Fixed the schema merging issue on remote loading and the logging on the gateway
  cli/generator-op-microservice/generators/microservice/templates/gql.service.ts
  packages/api-gateway-service/service.ts
  packages/feedback-service/service.ts
  packages/home-service/service.ts
  packages/notifications-service/service.ts
  packages/user-service/service.ts
Labels: bug

#448 fix(graphql-schema): Changed duplicate GraphQL types for User and Home
  packages/feedback-service/src/typedef.graphql
  packages/home-service/src/helpers.ts
  packages/home-service/src/typedef.graphql
  packages/home-service/src/types.d.ts
  packages/notifications-service/src/helpers.ts
  packages/notifications-service/src/notificationConfig/resolver.ts
  packages/notifications-service/src/notificationConfig/typedef.graphql
  packages/notifications-service/src/typedef.graphql
  packages/notifications-service/src/types.d.ts
  packages/user-service/src/typedef.graphql
Labels: bug

#417 fix(#415) - SPA - Authorization mapping for SPA and user group
  packages/user-profile-spa/.editorconfig
  packages/user-profile-spa/.env.example
  packages/user-profile-spa/.gitignore
  packages/user-profile-spa/README.md
  packages/user-profile-spa/angular.json
  packages/user-profile-spa/browserslist
  packages/user-profile-spa/e2e/protractor.conf.js
  packages/user-profile-spa/e2e/src/app.e2e-spec.ts
  packages/user-profile-spa/e2e/src/app.po.ts
  packages/user-profile-spa/e2e/tsconfig.json
  packages/user-profile-spa/jest.config.js
  packages/user-profile-spa/package-lock.json
  packages/user-profile-spa/package.json
  packages/user-profile-spa/set-env.ts
  packages/user-profile-spa/src/app/app-routing.module.ts
  packages/user-profile-spa/src/app/app.component.html
  packages/user-profile-spa/src/app/app.component.scss
  packages/user-profile-spa/src/app/app.component.spec.ts
  packages/user-profile-spa/src/app/app.component.ts
  packages/user-profile-spa/src/app/app.module.ts
  packages/user-profile-spa/src/app/app.service.spec.ts
  packages/user-profile-spa/src/app/app.service.ts
  packages/user-profile-spa/src/app/graphql.module.ts
  packages/user-profile-spa/src/app/helper.ts
  packages/user-profile-spa/src/app/mocks/user-profile-mock.ts
  packages/user-profile-spa/src/app/type.d.ts
  packages/user-profile-spa/src/app/user-profile-components/header/header.component.html
  packages/user-profile-spa/src/app/user-profile-components/header/header.component.scss
  packages/user-profile-spa/src/app/user-profile-components/header/header.component.spec.ts
  packages/user-profile-spa/src/app/user-profile-components/header/header.component.ts
  packages/user-profile-spa/src/app/user-profile-components/user-auth-details/user-auth-details.component.html
  packages/user-profile-spa/src/app/user-profile-components/user-auth-details/user-auth-details.component.scss
  packages/user-profile-spa/src/app/user-profile-components/user-auth-details/user-auth-details.component.spec.ts
  packages/user-profile-spa/src/app/user-profile-components/user-auth-details/user-auth-details.component.ts
  packages/user-profile-spa/src/app/user-profile-components/user-auth-details/user-auth-item/user-auth-item.component.html
  packages/user-profile-spa/src/app/user-profile-components/user-auth-details/user-auth-item/user-auth-item.component.scss
  packages/user-profile-spa/src/app/user-profile-components/user-auth-details/user-auth-item/user-auth-item.component.spec.ts
  packages/user-profile-spa/src/app/user-profile-components/user-auth-details/user-auth-item/user-auth-item.component.ts
  packages/user-profile-spa/src/app/user-profile-components/user-details/user-details.component.html
  packages/user-profile-spa/src/app/user-profile-components/user-details/user-details.component.scss
  packages/user-profile-spa/src/app/user-profile-components/user-details/user-details.component.spec.ts
  packages/user-profile-spa/src/app/user-profile-components/user-details/user-details.component.ts
  packages/user-profile-spa/src/app/user.gql.ts
  packages/user-profile-spa/src/assets/.gitkeep
  packages/user-profile-spa/src/environments/environment.prod.ts
  packages/user-profile-spa/src/environments/environment.ts
  packages/user-profile-spa/src/favicon.ico
  packages/user-profile-spa/src/index.html
  packages/user-profile-spa/src/main.ts
  packages/user-profile-spa/src/polyfills.ts
  packages/user-profile-spa/src/setup-jest.ts
  packages/user-profile-spa/src/styles.scss
  packages/user-profile-spa/tsconfig.app.json
  packages/user-profile-spa/tsconfig.json
  packages/user-profile-spa/tsconfig.spec.json
  packages/user-profile-spa/tslint.json
Labels: enhancement

#450 fix(#449) - Testing and fixing home-service for errors
  packages/home-service/src/e2e/home.spec.ts
  packages/home-service/src/helpers.ts
  packages/home-service/src/resolver.ts
  packages/home-service/src/typedef.graphql
Labels: bug, enhancement

#451 fix:403 Playground enabled for the api gateway
  packages/api-gateway-service/service.ts
Labels: bug

#453 fix(#452) - Home SPA needs improvement on the links
  docker-compose.yml
  packages/home-spa/src/app.js
  packages/home-spa/src/index.html
  packages/home-spa/src/js/controller.js
  packages/home-spa/src/js/service.js
  packages/home-spa/src/mocks/stub.js
  packages/home-spa/src/styles/common.scss
Labels: chore, enhancement

#457 fix(notifications-service): Validation for Notification Config source
  packages/notifications-service/src/notificationConfig/resolver.ts
Labels: bug

#458 hotfix(notification-service): typo in notifications endpoint
  packages/notifications-service/src/__tests__/notificationConfig.spec.ts
  packages/notifications-service/src/notificationConfig/resolver.ts
  packages/notifications-service/src/notificationConfig/typedef.graphql
Labels: bug

#460 fix(notifications-service): Patch for the NotificationConfig.source populate
  packages/notifications-service/src/__tests__/notificationConfig.spec.ts
  packages/notifications-service/src/notificationConfig/resolver.ts
  packages/notifications-service/src/notificationConfig/schema.ts
  packages/notifications-service/src/notificationConfig/typedef.graphql
Labels: bug

#461 fix(notification-service): Added id field in the getNotificationConfigsBy selectors
  packages/notifications-service/src/notificationConfig/resolver.ts
  packages/notifications-service/src/notificationConfig/schema.ts
  packages/notifications-service/src/notificationConfig/typedef.graphql
Labels: enhancement

#443 fix(#441) - Integration with notification microservice backend
  packages/notification-spa/package-lock.json
  packages/notification-spa/package.json
  packages/notification-spa/set-env.ts
  packages/notification-spa/src/app/app.component.spec.ts
  packages/notification-spa/src/app/app.component.ts
  packages/notification-spa/src/app/app.gql.ts
  packages/notification-spa/src/app/app.service.ts
  packages/notification-spa/src/app/graphql.module.ts
  packages/notification-spa/src/app/index/index.component.html
  packages/notification-spa/src/app/index/index.component.scss
  packages/notification-spa/src/app/index/index.component.ts
  packages/notification-spa/src/app/index/spa-notifications-list/spa-notifications-list.component.html
  packages/notification-spa/src/app/index/spa-notifications-list/spa-notifications-list.component.ts
  packages/notification-spa/src/app/manage-notification/manage-notification.component.html
  packages/notification-spa/src/app/manage-notification/manage-notification.component.scss
  packages/notification-spa/src/app/manage-notification/manage-notification.component.ts
  packages/notification-spa/src/app/manage-notification/type.d.ts
  packages/notification-spa/src/app/mocks/notificationItems.mock.ts
  packages/notification-spa/src/app/mocks/user.mock.ts
  packages/notification-spa/src/app/type.d.ts
Labels: chore, enhancement

#482 fix/#481 - Home-SPA shows mock data instead of backend data
  packages/home-spa/src/js/controller.js
  packages/home-spa/src/microservice-details.html
  packages/home-spa/webpack.config.js
Labels: bug
