Repository 1-Platform/one-platform, pull requests merged in 2020-07, with the labels that each got.

#501 fix(#500) - Rover user profile url over My Profile page
  packages/user-profile-spa/angular.json
  packages/user-profile-spa/src/app/user-profile-components/user-details/user-details.component.html
  packages/user-profile-spa/src/favicon.ico
  packages/user-profile-spa/src/index.html
Labels: chore

#503 fix(#502) - Change favicon from Angular to One Portal
  packages/feedback-spa/angular.json
  packages/home-spa/favicon.ico
  packages/notification-spa/angular.json
  packages/user-profile-spa/favicon.ico
Labels: bug

#523 feat(ssi-service): Refactored the OpNav using LitElements & Enhancements for OpFeedbackPanel
  docker-compose.yml
  packages/ssi-service/.env.example
  packages/ssi-service/README.md
  packages/ssi-service/package-lock.json
  packages/ssi-service/package.json
  packages/ssi-service/src/feedback-panel/feedback.css
  packages/ssi-service/src/feedback-panel/feedback.js
  packages/ssi-service/src/nav/api.js
  packages/ssi-service/src/nav/auth.js
  packages/ssi-service/src/nav/nav.css
  packages/ssi-service/src/nav/nav.js
  packages/ssi-service/tests/feedback-panel.spec.js
  packages/ssi-service/tests/nav.spec.js
  packages/ssi-service/webpack.config.js
Labels: enhancement

#521 fix(#520) - Update user-profile spa and notification spa to angular 10 and other fixes
  packages/notification-spa/.browserslistrc
  packages/notification-spa/e2e/tsconfig.json
  packages/notification-spa/package-lock.json
  packages/notification-spa/package.json
  packages/notification-spa/src/app/app.service.spec.ts
  packages/notification-spa/src/app/graphql.module.ts
  packages/notification-spa/src/app/helper.ts
  packages/notification-spa/src/global.d.ts
  packages/notification-spa/tsconfig.app.json
  packages/notification-spa/tsconfig.base.json
  packages/notification-spa/tsconfig.json
  packages/notification-spa/tsconfig.spec.json
  packages/notification-spa/tslint.json
  packages/user-profile-spa/.browserslistrc
  packages/user-profile-spa/e2e/tsconfig.json
  packages/user-profile-spa/favicon.ico
  packages/user-profile-spa/package-lock.json
  packages/user-profile-spa/package.json
  packages/user-profile-spa/tsconfig.app.json
  packages/user-profile-spa/tsconfig.base.json
  packages/user-profile-spa/tsconfig.json
  packages/user-profile-spa/tsconfig.spec.json
Labels: chore, dependencies

#536 fix(ssi): Minor fixes for Feedback Form and App Drawer icons
  packages/ssi-service/src/feedback-panel/feedback.css
  packages/ssi-service/src/feedback-panel/secrets.example.json
  packages/ssi-service/src/nav/nav.js
  packages/ssi-service/tests/feedback-panel.spec.js
  packages/ssi-service/tests/nav.spec.js
Labels: bug

#526 fix(gateway): Fixed the access issues on the API Gateway
  packages/api-gateway-service/package-lock.json
  packages/api-gateway-service/package.json
  packages/api-gateway-service/service.ts
Labels: enhancement

#539 fix(#504): Home service improvements
  packages/home-service/src/schema.ts
Labels: bug, chore, enhancement
