Repository 1-Platform/one-platform, pull requests merged in 2020-12, with the labels that each got.

#830 fix(user-group-service): Fixes user-group-service build error for _id type
  packages/user-group-service/src/types.d.ts
Labels: bug

#832 fix(#812) - Change the quotes on the home-page of One platform
  packages/home-spa/src/img/begin-quote.svg
  packages/home-spa/src/img/quotes.svg
  packages/home-spa/src/styles/main.scss
Labels: enhancement

#831 fix(ssi-path): Changes the ssi default path to /.ssi
  docker-compose.yml
  packages/feedback-spa/src/index.html
  packages/home-spa/src/404.html
  packages/home-spa/src/contact-us/index.html
  packages/home-spa/src/index.html
  packages/notification-spa/src/index.html
  packages/search-spa/src/index.html
  packages/ssi-service/.env.example
  packages/ssi-service/public/index.html
  packages/user-group-spa/public/index.html
  packages/user-profile-spa/src/index.html
Labels: chore

#816 feat(notifications-service): Adds custom template support in Notifications Service
  packages/documentation-spa/docs/microservices/notifications/notifications-service.md
  packages/notifications-service/.env.example
  packages/notifications-service/README.md
  packages/notifications-service/package-lock.json
  packages/notifications-service/package.json
  packages/notifications-service/service.ts
  packages/notifications-service/src/broadcaster.ts
  packages/notifications-service/src/engine.ts
  packages/notifications-service/src/helpers.ts
  packages/notifications-service/src/notificationConfig/schema.ts
  packages/notifications-service/src/notificationTemplates/resolver.ts
  packages/notifications-service/src/notificationTemplates/schema.ts
  packages/notifications-service/src/notificationTemplates/typedef.graphql
  packages/notifications-service/src/notificationTemplates/types.d.ts
  packages/notifications-service/src/resolver.ts
  packages/notifications-service/src/typedef.graphql
  packages/notifications-service/src/types.d.ts
Labels: enhancement
