Repository 1-Platform/one-platform, pull requests merged in 2020-08, with the labels that each got.

#565 enhancement(notifications-service): Added targets to the listArchivedNotifications
  packages/notifications-service/src/broadcaster.ts
  packages/notifications-service/src/engine.ts
  packages/notifications-service/src/resolver.ts
  packages/notifications-service/src/typedef.graphql
  packages/notifications-service/src/types.d.ts
  packages/ssi-service/src/nav/api.js
  packages/ssi-service/src/nav/nav.js
Labels: enhancement

#590 feat(ssi): Contextual theming for Toast messages
  packages/ssi-service/README.md
  packages/ssi-service/src/nav/nav.css
  packages/ssi-service/src/nav/nav.js
Labels: enhancement

#568 fix(ssi): Changed the auth library to basic keycloak-js
  docker-compose.yml
  packages/feedback-spa/src/index.html
  packages/home-spa/src/404.html
  packages/home-spa/src/contact-us.html
  packages/home-spa/src/index.html
  packages/home-spa/src/microservice-details.html
  packages/notification-spa/src/index.html
  packages/ssi-service/.env.example
  packages/ssi-service/README.md
  packages/ssi-service/package-lock.json
  packages/ssi-service/package.json
  packages/ssi-service/src/auth.js
  packages/ssi-service/src/default.html
  packages/ssi-service/src/feedback-panel/feedback-lit.js
  packages/ssi-service/src/nav/nav.js
  packages/ssi-service/tests/feedback-panel.spec.js
  packages/ssi-service/tests/setupJest.js
  packages/ssi-service/webpack.config.js
  packages/user-profile-spa/src/index.html
Labels: bug, enhancement

#588 fix(ssi): Dynamic update for SPA dropdown in Feedback form
  packages/ssi-service/src/feedback-panel/feedback.js
Labels: bug

#594 fix(api-gateway): API Gateway auth fixes and some code cleanup
  packages/api-gateway-service/.env.example
  packages/api-gateway-service/service.ts
  packages/api-gateway-service/src/helpers.ts
Labels: bug, chore

#593 chore(ssi): SSI readme cleanup & spaship config for SPAs
  packages/feedback-spa/spaship.yaml
  packages/feedback-spa/src/module.d.ts
  packages/home-spa/spaship.yaml
  packages/notification-spa/spaship.yaml
  packages/ssi-service/screenshots/danger-Toast.png
  packages/ssi-service/screenshots/info-toast.png
  packages/ssi-service/screenshots/simple-toast.png
  packages/ssi-service/screenshots/success-toast.png
  packages/ssi-service/screenshots/toasts.png
  packages/ssi-service/screenshots/warning-toast.png
  packages/ssi-service/spaship.yaml
  packages/user-profile-spa/spaship.yaml
  packages/user-profile-spa/src/app/module.d.ts
Labels: chore

#592 fix(home-spa): Patch for Request authorization in Home controller
  packages/home-spa/src/js/controller.js
  packages/home-spa/src/js/service.js
Labels: enhancement

#595 fix(home-spa): Fixed some broken img assets and links
  packages/home-spa/package-lock.json
  packages/home-spa/package.json
  packages/home-spa/src/404.html
  packages/home-spa/src/app.js
  packages/home-spa/src/contact-us/index.html
  packages/home-spa/src/index.html
  packages/home-spa/src/js/controller.js
  packages/home-spa/src/styles/common.scss
  packages/home-spa/src/styles/main.scss
  packages/home-spa/webpack.config.js
Labels: bug

#615 fix(ssi): Added auth token to websocket connection params
  packages/ssi-service/public/index.html
  packages/ssi-service/src/default.html
  packages/ssi-service/src/nav/api.js
  packages/ssi-service/src/nav/nav.js
Labels: bug

#618 fix(#617) - Incorrect links and other fixes for beta and qa instances
  packages/home-spa/src/404.html
  packages/home-spa/src/contact-us/index.html
  packages/home-spa/src/index.html
  packages/home-spa/src/js/controller.js
  packages/home-spa/src/js/vendor/lib
  packages/home-spa/src/styles/main.scss
Labels: bug

#620 fix(#619) - Home-SPA illustration height breaking for smaller screens
  packages/home-spa/src/styles/main.scss
Labels: bug

#625 fix(#623) - pfe-toast import error in Notifications SPA
  packages/notification-spa/package-lock.json
  packages/notification-spa/package.json
  packages/notification-spa/src/app/app.gql.ts
  packages/notification-spa/src/app/app.module.ts
  packages/notification-spa/src/app/helper.ts
  packages/notification-spa/src/app/index/index.component.html
  packages/notification-spa/src/app/index/index.component.ts
  packages/notification-spa/src/app/manage-notification/manage-notification.component.html
  packages/notification-spa/src/app/manage-notification/manage-notification.component.scss
  packages/notification-spa/src/app/manage-notification/manage-notification.component.ts
  packages/notification-spa/src/app/module.d.ts
  packages/notification-spa/src/favicon.ico
Labels: bug

#624 Error handling for subscriptions, and version bump
  packages/ssi-service/package-lock.json
  packages/ssi-service/package.json
  packages/ssi-service/src/nav/nav.js
  packages/ssi-service/webpack.config.js
Labels: chore

#650 chore(renovate): Group minors & patches together
  renovate.json
Labels: chore, dependencies

#653 feat:(555, 554, 550) Search Microservice
  docker-compose.yml
  packages/api-gateway-service/.env.example
  packages/api-gateway-service/service.ts
  packages/search-service/.dockerignore
  packages/search-service/.env.example
  packages/search-service/.gitignore
  packages/search-service/Dockerfile
  packages/search-service/README.md
  packages/search-service/jest.config.js
  packages/search-service/package-lock.json
  packages/search-service/package.json
  packages/search-service/service.ts
  packages/search-service/src/e2e/mock.json
  packages/search-service/src/e2e/search.spec.ts
  packages/search-service/src/helpers.ts
  packages/search-service/src/resolver.ts
  packages/search-service/src/typedef.graphql
  packages/search-service/src/types.d.ts
  packages/search-service/tsconfig.json
  packages/search-service/tslint.json
  packages/search-service/webpack.common.js
  packages/search-service/webpack.dev.js
  packages/search-service/webpack.prod.js
Labels: enhancement

#626 feat(user-groups): Graphql Queries and Mutations and some code cleanup
  docker-compose.yml
  packages/user-group-service/.dockerignore
  packages/user-group-service/.env.example
  packages/user-group-service/.gitignore
  packages/user-group-service/Dockerfile
  packages/user-group-service/README.md
  packages/user-group-service/jest.config.js
  packages/user-group-service/package-lock.json
  packages/user-group-service/package.json
  packages/user-group-service/service.ts
  packages/user-group-service/src/e2e/mock.json
  packages/user-group-service/src/e2e/user.spec.ts
  packages/user-group-service/src/groups/resolver.ts
  packages/user-group-service/src/groups/schema.ts
  packages/user-group-service/src/groups/typedef.graphql
  packages/user-group-service/src/helpers.ts
  packages/user-group-service/src/types.d.ts
  packages/user-group-service/src/users/cron.ts
  packages/user-group-service/src/users/resolver.ts
  packages/user-group-service/src/users/schema.ts
  packages/user-group-service/src/users/typedef.graphql
  packages/user-group-service/tsconfig.json
  packages/user-group-service/tslint.json
  packages/user-group-service/webpack.common.js
  packages/user-group-service/webpack.dev.js
  packages/user-group-service/webpack.prod.js
  packages/user-service/src/cron.ts
  packages/user-service/src/resolver.ts
Labels: enhancement

#652 feat(user-group-spa): 👥 Implementation of User Group SPA
  docker-compose.yml
  packages/user-group-spa/.gitignore
  packages/user-group-spa/README.md
  packages/user-group-spa/package-lock.json
  packages/user-group-spa/package.json
  packages/user-group-spa/public/.htaccess
  packages/user-group-spa/public/config.js
  packages/user-group-spa/public/index.html
  packages/user-group-spa/src/App.css
  packages/user-group-spa/src/App.jsx
  packages/user-group-spa/src/App.test.js
  packages/user-group-spa/src/components/Form.jsx
  packages/user-group-spa/src/components/Group.jsx
  packages/user-group-spa/src/components/Home.jsx
  packages/user-group-spa/src/components/NotFound.jsx
  packages/user-group-spa/src/components/User.jsx
  packages/user-group-spa/src/index.css
  packages/user-group-spa/src/index.js
  packages/user-group-spa/src/serviceWorker.js
  packages/user-group-spa/src/services/FetchClient.js
  packages/user-group-spa/src/services/GqlQueries.js
  packages/user-group-spa/src/services/GroupsAPI.js
  packages/user-group-spa/src/setupTests.js
Labels: enhancement

#654 feat:(555, 554) Search SPA Readiness
  packages/search-spa/.browserslistrc
  packages/search-spa/.editorconfig
  packages/search-spa/.gitignore
  packages/search-spa/README.md
  packages/search-spa/angular.json
  packages/search-spa/e2e/protractor.conf.js
  packages/search-spa/e2e/src/app.e2e-spec.ts
  packages/search-spa/e2e/src/app.po.ts
  packages/search-spa/e2e/tsconfig.json
  packages/search-spa/jest.config.js
  packages/search-spa/karma.conf.js
  packages/search-spa/package-lock.json
  packages/search-spa/package.json
  packages/search-spa/set-env.ts
  packages/search-spa/src/app/app-routing.module.ts
  packages/search-spa/src/app/app.component.html
  packages/search-spa/src/app/app.component.scss
  packages/search-spa/src/app/app.component.spec.ts
  packages/search-spa/src/app/app.component.ts
  packages/search-spa/src/app/app.gql.ts
  packages/search-spa/src/app/app.module.ts
  packages/search-spa/src/app/app.service.spec.ts
  packages/search-spa/src/app/app.service.ts
  packages/search-spa/src/app/graphql.module.ts
  packages/search-spa/src/app/search/search.component.html
  packages/search-spa/src/app/search/search.component.scss
  packages/search-spa/src/app/search/search.component.spec.ts
  packages/search-spa/src/app/search/search.component.ts
  packages/search-spa/src/app/testing/mocks/result.mock.ts
  packages/search-spa/src/app/types.d.ts
  packages/search-spa/src/assets/.gitkeep
  packages/search-spa/src/assets/icons/dsal.svg
  packages/search-spa/src/assets/icons/feedback.svg
  packages/search-spa/src/assets/icons/mod.svg
  packages/search-spa/src/assets/icons/outages.svg
  packages/search-spa/src/environments/environment.prod.ts
  packages/search-spa/src/environments/environment.ts
  packages/search-spa/src/favicon.ico
  packages/search-spa/src/index.html
  packages/search-spa/src/main.ts
  packages/search-spa/src/polyfills.ts
  packages/search-spa/src/setup-jest.ts
  packages/search-spa/src/styles.scss
  packages/search-spa/tsconfig.app.json
  packages/search-spa/tsconfig.base.json
  packages/search-spa/tsconfig.json
  packages/search-spa/tsconfig.spec.json
  packages/search-spa/tslint.json
  packages/ssi-service/package.json
  packages/ssi-service/src/nav/nav.js
Labels: enhancement
