Repository 1-Platform/one-platform, pull requests merged in 2021-04, with the labels that each got.

#927 Docs(blog): March 2021 State of One Platform blog post
  packages/documentation-spa/blog/2021-04-12-state-of-one-platform-mar-2021.md
Labels: documentation

#924 fix(#920) - Layout styles load 1-2 seconds after page load on the One Platform Home Page
  packages/home-spa/package-lock.json
  packages/home-spa/package.json
  packages/home-spa/src/index.html
  packages/home-spa/src/js/controller.js
Labels: bug, chore

#929 fix(#928) - 404 page ui breaks on stage and prod due to > 8 apps being displayed in the same row
  packages/home-spa/src/js/controller.js
  packages/home-spa/src/styles/main.scss
Labels: bug, chore

#931 Feat(#666): Implementation of rover integration.
  packages/user-group-service/.env.example
  packages/user-group-service/package-lock.json
  packages/user-group-service/src/groups/resolver.ts
  packages/user-group-service/src/groups/typedef.graphql
  packages/user-group-service/src/helpers.ts
  packages/user-group-service/src/users/cron.ts
  packages/user-group-service/src/users/resolver.ts
  packages/user-group-service/src/users/schema.ts
  packages/user-group-service/src/users/typedef.graphql
Labels: enhancement
