Repository 1-Platform/one-platform, pull requests merged in 2021-08, with the labels that each got.

#1056 hot-fix(ssi) - Added app path for hosted and built-in services
  packages/ssi-service/src/nav/nav.js
Labels: bug

#1057 Lighthouse UI changes and fixed broken test of LH
  packages/lighthouse-spa/package.json
  packages/lighthouse-spa/src/app/app-routing.module.ts
  packages/lighthouse-spa/src/app/app.component.html
  packages/lighthouse-spa/src/app/dashboard/components/property-card/property-card.component.html
  packages/lighthouse-spa/src/app/dashboard/dashboard-routing.module.ts
  packages/lighthouse-spa/src/app/dashboard/dashboard.module.ts
  packages/lighthouse-spa/src/app/dashboard/dashboard.service.spec.ts
  packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.html
  packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.spec.ts
  packages/lighthouse-spa/src/app/dashboard/pages/dashboard/dashboard.component.html
  packages/lighthouse-spa/src/app/dashboard/pages/dashboard/dashboard.component.scss
  packages/lighthouse-spa/src/app/dashboard/pages/dashboard/dashboard.component.ts
  packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.html
  packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.scss
  packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.spec.ts
  packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.ts
  packages/lighthouse-spa/src/app/home/components/home/home.component.scss
  packages/lighthouse-spa/src/app/playground/components/home/home.component.html
  packages/lighthouse-spa/src/app/playground/components/home/home.component.scss
  packages/lighthouse-spa/src/app/playground/components/home/home.component.spec.ts
  packages/lighthouse-spa/src/app/playground/components/home/home.component.ts
  packages/lighthouse-spa/src/app/playground/playground-routing.module.ts
  packages/lighthouse-spa/src/app/playground/playground.module.ts
  packages/lighthouse-spa/src/app/shared/components/lhtag-line-steps/lhtag-line-steps.component.html
  packages/lighthouse-spa/src/app/shared/components/lhtag-line-steps/lhtag-line-steps.component.scss
  packages/lighthouse-spa/src/app/shared/components/lhtag-line-steps/lhtag-line-steps.component.spec.ts
  packages/lighthouse-spa/src/app/shared/components/lhtag-line-steps/lhtag-line-steps.component.ts
  packages/lighthouse-spa/src/app/shared/layouts/app-layout/app-layout.component.html
  packages/lighthouse-spa/src/app/shared/layouts/app-layout/app-layout.component.scss
  packages/lighthouse-spa/src/app/shared/layouts/app-layout/app-layout.component.spec.ts
  packages/lighthouse-spa/src/app/shared/layouts/app-layout/app-layout.component.ts
  packages/lighthouse-spa/src/app/shared/shared.module.ts
  packages/lighthouse-spa/src/environments/environment.prod.ts
  packages/lighthouse-spa/src/environments/environment.ts
Labels: enhancement

#1060 chore(api-gateway): Adds configurability for API Gateway Base URL
  packages/api-gateway-service/.env.example
  packages/api-gateway-service/service.ts
  packages/api-gateway-service/src/remote-schema.ts
Labels: chore

#1061 hotfix(dev-console): Fixes typos in developer console toast messages
  packages/developer-console-spa/src/components/AddAppForm.tsx
  packages/developer-console-spa/src/components/AppSettings.tsx
Labels: bug

#1063 fix(#1059) - Toaster notification across entire platform
  packages/feedback-spa/src/views/Home.vue
Labels: chore

#1054 feat(dev-console): Adds feedback config page
  packages/developer-console-spa/.env.example
  packages/developer-console-spa/src/components/ConfigureFeedback.tsx
  packages/developer-console-spa/src/components/Header.tsx
  packages/developer-console-spa/src/components/Sidebar.tsx
  packages/developer-console-spa/src/context/AppContext.tsx
  packages/developer-console-spa/src/hooks/useFeedbackConfig.ts
  packages/developer-console-spa/src/services/feedbackConfig.ts
  packages/developer-console-spa/src/utils/gql-queries/app-feedback-config.ts
  packages/developer-console-spa/src/utils/gql-queries/index.ts
  packages/developer-console-spa/src/utils/gqlClient.ts
Labels: enhancement

#1065 feat(1370): updated ui of dashboard, cards and fixed broken links
  packages/lighthouse-spa/package-lock.json
  packages/lighthouse-spa/package.json
  packages/lighthouse-spa/set-env.ts
  packages/lighthouse-spa/src/app/dashboard/dashboard.gql.ts
  packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.html
  packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.scss
  packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.ts
  packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.html
  packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.scss
  packages/lighthouse-spa/src/app/dashboard/types.d.ts
  packages/lighthouse-spa/src/app/playground/components/home/home.component.html
  packages/lighthouse-spa/src/app/playground/components/home/home.component.scss
  packages/lighthouse-spa/src/app/shared/layouts/app-layout/app-layout.component.html
  packages/lighthouse-spa/src/app/shared/layouts/app-layout/app-layout.component.scss
  packages/lighthouse-spa/src/app/shared/layouts/app-layout/app-layout.component.ts
  packages/lighthouse-spa/src/index.html
Labels: enhancement

#1074 feat(rproxy): Created a reverse proxy service for internal service API routing.
  .github/workflows/build-reverse-proxy-service.yml
  docker-compose.yml
  packages/reverse-proxy-service/.env.example
  packages/reverse-proxy-service/.gitignore
  packages/reverse-proxy-service/Dockerfile
  packages/reverse-proxy-service/README.md
  packages/reverse-proxy-service/jest.config.js
  packages/reverse-proxy-service/nodemon.json
  packages/reverse-proxy-service/package-lock.json
  packages/reverse-proxy-service/package.json
  packages/reverse-proxy-service/src/app.ts
  packages/reverse-proxy-service/src/config/env.ts
  packages/reverse-proxy-service/src/couchdb/index.ts
  packages/reverse-proxy-service/src/couchdb/resolver.ts
  packages/reverse-proxy-service/src/index.ts
  packages/reverse-proxy-service/src/middleware/jwtAuth.ts
  packages/reverse-proxy-service/src/spec/app.spec.ts
  packages/reverse-proxy-service/src/spec/couchdb.spec.ts
  packages/reverse-proxy-service/src/spec/jwtAuth.spec.ts
  packages/reverse-proxy-service/src/utils/setupJest.ts
  packages/reverse-proxy-service/src/utils/verifyJwtToken.ts
  packages/reverse-proxy-service/tsconfig.json
Labels: enhancement

#1069 feat(1332): Implemented SSI library
  packages/opc-base/.gitignore
  packages/opc-base/README.md
  packages/opc-base/babel.config.js
  packages/opc-base/dev/config.example.js
  packages/opc-base/dev/index.html
  packages/opc-base/docs/opc-base.md
  packages/opc-base/docs/opc-provider.md
  packages/opc-base/jest.config.js
  packages/opc-base/package-lock.json
  packages/opc-base/package.json
  packages/opc-base/rollup.config.js
  packages/opc-base/src/assets/logo.svg
  packages/opc-base/src/components/opc-drawer-footer/opc-drawer-footer.styles.ts
  packages/opc-base/src/components/opc-drawer-footer/opc-drawer-footer.ts
  packages/opc-base/src/components/opc-loader/opc-loader.styles.ts
  packages/opc-base/src/components/opc-loader/opc-loader.ts
  packages/opc-base/src/components/opc-menu-drawer/opc-avatar/opc-avatar.styles.ts
  packages/opc-base/src/components/opc-menu-drawer/opc-avatar/opc-avatar.ts
  packages/opc-base/src/components/opc-notification-drawer/opc-filter-chip/opc-filter-chip.styles.ts
  packages/opc-base/src/components/opc-notification-drawer/opc-filter-chip/opc-filter-chip.ts
  packages/opc-base/src/components/opc-toast/opc-toast.styles.ts
  packages/opc-base/src/components/opc-toast/opc-toast.test.ts
  packages/opc-base/src/components/opc-toast/opc-toast.ts
  packages/opc-base/src/components/opc-toast/types.ts
  packages/opc-base/src/config/graphql.ts
  packages/opc-base/src/config/types.ts
  packages/opc-base/src/custom.d.ts
  packages/opc-base/src/gql/opc-app-layout.ts
  packages/opc-base/src/gql/types.ts
  packages/opc-base/src/keycloakAuthProvider/keycloakAuthProvider.ts
  packages/opc-base/src/keycloakAuthProvider/types.ts
  packages/opc-base/src/opc-base/opc-base.test.ts
  packages/opc-base/src/opc-base/opc-base.ts
  packages/opc-base/src/opc-base/types.ts
  packages/opc-base/src/opc-provider/opc-provider.helper.ts
  packages/opc-base/src/opc-provider/opc-provider.styles.ts
  packages/opc-base/src/opc-provider/opc-provider.test.ts
  packages/opc-base/src/opc-provider/opc-provider.ts
  packages/opc-base/src/opc-provider/types.ts
  packages/opc-base/src/types.d.ts
  packages/opc-base/test/opc-provider.js
  packages/opc-base/tsconfig.json
Labels: enhancement

#1083 fix(dev-console): Fixes scroll overflow in dev console sidebar
  packages/developer-console-spa/src/components/Sidebar.css
Labels: bug

#1085 chore(#1084) - Update SPAship config file (spaship.yml) in all SPAs to add buildDir
  packages/api-catalog-spa/spaship.yaml
  packages/developer-console-spa/spaship.yaml
  packages/documentation-spa/spaship.yaml
  packages/feedback-spa/spaship.yaml
  packages/home-spa/spaship.yaml
  packages/lighthouse-spa/spaship.yaml
  packages/notification-spa/spaship.yaml
  packages/search-spa/spaship.yaml
  packages/user-group-spa/spaship.yaml
Labels: chore

#1090 hotfix: changed opc-base doc redirect to absolute and fixed typo in doc
  packages/opc-base/README.md
  packages/opc-base/docs/opc-provider.md
Labels: documentation
