Repository 1-Platform/one-platform, pull requests merged in 2021-02, with the labels that each got.

#875 fix(api-gateway): Removes case sensitivity from authorization header
  packages/api-gateway-service/service.ts
Labels: chore

#876 Docs(blog): January 2021 State of One Platform blog post
  packages/documentation-spa/blog/2021-02-08-state-of-one-platform-jan-2021.md
Labels: documentation

#868 feat: Feedback Microservice with Gitlab, Jira and Github Integrations with Email Support.
  packages/feedback-service/.env.example
  packages/feedback-service/Dockerfile
  packages/feedback-service/README.md
  packages/feedback-service/jest.config.js
  packages/feedback-service/package-lock.json
  packages/feedback-service/package.json
  packages/feedback-service/service.ts
  packages/feedback-service/src/e2e/feedback.spec.ts
  packages/feedback-service/src/e2e/mock.json
  packages/feedback-service/src/helpers.ts
  packages/feedback-service/src/resolver.ts
  packages/feedback-service/src/schema.ts
  packages/feedback-service/src/typedef.graphql
  packages/feedback-service/src/types.d.ts
  packages/home-service/src/schema.ts
  packages/home-service/src/typedef.graphql
  packages/home-service/src/types.d.ts
Labels: enhancement

#884 fix(#877) - Unify all docs SPAs under single SPA
  packages/common/blogs.json
  packages/home-spa/README.md
  packages/home-spa/package-lock.json
  packages/home-spa/src/app.js
  packages/home-spa/src/img/blog_illustration.png
  packages/home-spa/src/img/components_illustration.png
  packages/home-spa/src/img/faq_illustration.png
  packages/home-spa/src/img/microservices_illustration.png
  packages/home-spa/src/index.html
  packages/home-spa/src/styles/common.scss
  packages/home-spa/src/tests/404.spec.js
Labels: documentation, enhancement

#878 949 - Fixed the SPA Validation as part of data updation and synced the dependencies
  packages/search-spa/package-lock.json
  packages/search-spa/package.json
  packages/search-spa/src/app/app.component.spec.ts
  packages/search-spa/src/app/app.service.ts
  packages/search-spa/src/app/search/search.component.html
  packages/search-spa/src/app/search/search.component.spec.ts
  packages/search-spa/src/app/search/search.component.ts
  packages/search-spa/src/app/testing/mocks/result.mock.ts
  packages/search-spa/src/main.ts
  packages/search-spa/src/module.d.ts
Labels: chore

#885 chore(npm): Upgraded npm packages with minor security updates
  packages/api-gateway-service/package-lock.json
  packages/api-gateway-service/package.json
  packages/documentation-spa/package-lock.json
  packages/home-service/package-lock.json
  packages/home-spa/package-lock.json
  packages/home-spa/package.json
  packages/notification-spa/package-lock.json
  packages/notifications-service/package-lock.json
  packages/search-service/package-lock.json
  packages/search-spa/package-lock.json
  packages/ssi-service/package-lock.json
  packages/ssi-service/package.json
  packages/user-group-service/package-lock.json
  packages/user-group-spa/package-lock.json
Labels: chore
