Repository 1-Platform/one-platform, pull requests merged in 2021-09, with the labels that each got.

#1098 hotfix: changed opc-base pkg version to beta
  packages/opc-base/package.json
Labels: enhancement

#1091 API Catalog Microservice with notifications and namespaces services
  .vscode/extensions.json
  packages/api-catalog-service/.dockerignore
  packages/api-catalog-service/.env.example
  packages/api-catalog-service/.eslintignore
  packages/api-catalog-service/.eslintrc.js
  packages/api-catalog-service/.gitignore
  packages/api-catalog-service/Dockerfile
  packages/api-catalog-service/README.md
  packages/api-catalog-service/jest.config.js
  packages/api-catalog-service/package-lock.json
  packages/api-catalog-service/package.json
  packages/api-catalog-service/service.ts
  packages/api-catalog-service/src/e2e/api-catalog.spec.ts
  packages/api-catalog-service/src/e2e/mock.json
  packages/api-catalog-service/src/namespace/resolver.ts
  packages/api-catalog-service/src/namespace/schema.ts
  packages/api-catalog-service/src/namespace/typedef.graphql
  packages/api-catalog-service/src/setup/database.ts
  packages/api-catalog-service/src/setup/env.ts
  packages/api-catalog-service/src/shared/cron/cron.ts
  packages/api-catalog-service/src/shared/cron/index.ts
  packages/api-catalog-service/src/shared/emails/update-email-config.ts
  packages/api-catalog-service/src/shared/helpers.ts
  packages/api-catalog-service/src/shared/typedef.graphql
  packages/api-catalog-service/src/types.d.ts
  packages/api-catalog-service/tsconfig.json
  packages/api-catalog-service/webpack.common.js
  packages/api-catalog-service/webpack.dev.js
  packages/api-catalog-service/webpack.prod.js
Labels: enhancement

#1102 doc(#1101) -Documentation - Add new dev onboarding guide in OP home page
  packages/documentation-spa/docs/onboarding-guide/onboarding-guide.md
  packages/documentation-spa/package-lock.json
  packages/documentation-spa/package.json
  packages/documentation-spa/sidebars.js
Labels: documentation

#1100 Included test cases, subscriptions and schema pulling for API Catalog
  packages/api-catalog-service/src/e2e/api-catalog.spec.ts
  packages/api-catalog-service/src/e2e/mock.json
  packages/api-catalog-service/src/namespace/resolver.ts
  packages/api-catalog-service/src/namespace/typedef.graphql
  packages/api-catalog-service/src/shared/cron/cron.ts
  packages/api-catalog-service/src/shared/emails/update-email-config.ts
  packages/api-catalog-service/src/shared/helpers.ts
  packages/api-catalog-service/src/types.d.ts
Labels: bug, enhancement, chore

#1110 hotfix: changed opc-base version to 1.0.0-beta
  packages/opc-base/package-lock.json
  packages/opc-base/package.json
Labels: enhancement

#1112 hotfix: removed opc-base private field in package.json
  packages/opc-base/package.json
Labels: bug

#1113 hotfix: fixed opc-base package.json for publishing
  packages/opc-base/package.json
Labels: bug

#1105 fix(renovate): Fixes the renovate config schedule
  renovate.json
Labels: bug

#1107 Feat#1360: Lighthouse createProject mutation changes
  packages/lighthouse-service/src/audit-manager/typedef.graphql
  packages/lighthouse-service/src/lighthouse-spa-config/resolver.ts
  packages/lighthouse-service/src/property-manager/helpers.ts
  packages/lighthouse-service/src/property-manager/resolver.ts
  packages/lighthouse-service/src/property-manager/typedef.graphql
Labels: enhancement

#1108 feat(1419,1421,1411): Implemented leaderboard and connected directly with LH CI database from LH service
  packages/lighthouse-service/.env.example
  packages/lighthouse-service/package-lock.json
  packages/lighthouse-service/package.json
  packages/lighthouse-service/src/audit-manager/resolver.ts
  packages/lighthouse-service/src/audit-manager/typedef.graphql
  packages/lighthouse-service/src/lighthouse-db-manager/README.md
  packages/lighthouse-service/src/lighthouse-db-manager/index.ts
  packages/lighthouse-service/src/lighthouse-db-manager/lighthouse-db-manager.ts
  packages/lighthouse-service/src/lighthouse-db-manager/models/build.ts
  packages/lighthouse-service/src/lighthouse-db-manager/models/project.ts
  packages/lighthouse-service/src/lighthouse-db-manager/models/statistic.ts
  packages/lighthouse-service/src/lighthouse-db-manager/sequelize.ts
  packages/lighthouse-service/src/lighthouse-db-manager/types.ts
  packages/lighthouse-service/src/types.d.ts
Labels: enhancement

#1097 Feat(#1360): Implemented Lighthouse configuration in dev console
  packages/developer-console-spa/package.json
  packages/developer-console-spa/src/App.tsx
  packages/developer-console-spa/src/assets/lighthouse_illust.png
  packages/developer-console-spa/src/components/AppIndex.css
  packages/developer-console-spa/src/components/ConfigureLighthouse.tsx
  packages/developer-console-spa/src/components/Sidebar.tsx
  packages/developer-console-spa/src/components/lighthouse/CreateProjectForm.tsx
  packages/developer-console-spa/src/components/lighthouse/LinkProjectForm.tsx
  packages/developer-console-spa/src/hooks/useLighthouseConfig.ts
  packages/developer-console-spa/src/services/feedbackConfig.ts
  packages/developer-console-spa/src/services/lighthouse.ts
  packages/developer-console-spa/src/types.ts
  packages/developer-console-spa/src/typings.d.ts
  packages/developer-console-spa/src/utils/gql-queries/create-lh-projects.ts
  packages/developer-console-spa/src/utils/gql-queries/create-lh-spa-config.ts
  packages/developer-console-spa/src/utils/gql-queries/delete-lh-spa-config.ts
  packages/developer-console-spa/src/utils/gql-queries/index.ts
  packages/developer-console-spa/src/utils/gql-queries/lh-spa-config-by-appId.ts
  packages/developer-console-spa/src/utils/gql-queries/list-lh-projects-branches.ts
  packages/developer-console-spa/src/utils/gql-queries/list-lh-projects.ts
  packages/developer-console-spa/src/utils/gqlClient.ts
Labels: enhancement

#1139 feat(apps-service): Created mutations for database mgmt in App Service
  packages/apps-service/.env.example
  packages/apps-service/README.md
  packages/apps-service/package-lock.json
  packages/apps-service/package.json
  packages/apps-service/src/@types/apps/index.d.ts
  packages/apps-service/src/modules/apps/model.ts
  packages/apps-service/src/modules/apps/resolver.ts
  packages/apps-service/src/modules/apps/schema.gql.ts
  packages/apps-service/src/services/couchdb.ts
  packages/apps-service/src/setup/env.ts
  packages/apps-service/src/utils/apps-helper.ts
  packages/apps-service/tsconfig.json
Labels: enhancement

#1140 Adds user prefix in the userCtx role for couchdb
  packages/reverse-proxy-service/src/couchdb/resolver.ts
Labels: chore

#1119 fix:1447 Included github image configuration, docker configuration & Pagination to the API in API Catalog
  .github/workflows/build-api-catalog-service.yml
  docker-compose.yml
  packages/api-catalog-service/package-lock.json
  packages/api-catalog-service/package.json
  packages/api-catalog-service/src/e2e/api-catalog.spec.ts
  packages/api-catalog-service/src/e2e/mock.json
  packages/api-catalog-service/src/namespace/resolver.ts
  packages/api-catalog-service/src/namespace/schema.ts
  packages/api-catalog-service/src/namespace/typedef.graphql
  packages/api-catalog-service/src/setup/database.ts
  packages/api-catalog-service/src/shared/cron/cron.ts
  packages/api-catalog-service/src/shared/cron/index.ts
  packages/api-catalog-service/src/shared/emails/update-email-config.ts
  packages/api-catalog-service/src/shared/helpers.ts
  packages/api-catalog-service/src/types.d.ts
Labels: documentation, dependencies

#1128 Feat#1473: Consuming LHproject query changes in dev console.
  packages/developer-console-spa/src/components/lighthouse/LinkProjectForm.tsx
  packages/developer-console-spa/src/services/lighthouse.ts
  packages/developer-console-spa/src/types.ts
  packages/developer-console-spa/src/utils/gql-queries/list-lh-projects-branches.ts
  packages/developer-console-spa/src/utils/gql-queries/list-lh-projects.ts
Labels: enhancement

#1149 feat(apps): Add description & permissions to db
  packages/apps-service/src/@types/apps/index.d.ts
  packages/apps-service/src/modules/apps/model.ts
  packages/apps-service/src/modules/apps/resolver.ts
  packages/apps-service/src/modules/apps/schema.gql.ts
Labels: enhancement

#1147 feat(1488): opcBase and opc-provider bug fix and ui improvement with …
  packages/opc-base/dev/index.html
  packages/opc-base/docs/opc-base.md
  packages/opc-base/docs/opc-provider.md
  packages/opc-base/package-lock.json
  packages/opc-base/package.json
  packages/opc-base/src/components/opc-loader/opc-loader.styles.ts
  packages/opc-base/src/components/opc-loader/opc-loader.ts
  packages/opc-base/src/components/opc-notification-drawer/opc-filter-chip/opc-filter-chip.styles.ts
  packages/opc-base/src/components/opc-toast/opc-toast.styles.ts
  packages/opc-base/src/components/opc-toast/opc-toast.ts
  packages/opc-base/src/custom.d.ts
  packages/opc-base/src/opc-provider/opc-provider.ts
Labels: enhancement

#1143 chore(reverse-proxy-service): Added winston for better logging in reverse-proxy
  packages/reverse-proxy-service/package-lock.json
  packages/reverse-proxy-service/package.json
  packages/reverse-proxy-service/src/app.ts
  packages/reverse-proxy-service/src/config/env.ts
  packages/reverse-proxy-service/src/index.ts
  packages/reverse-proxy-service/src/middleware/jwtAuth.ts
  packages/reverse-proxy-service/src/utils/logger.ts
Labels: chore

#1141 chore(docker-compose): Added couchdb service to the main docker-compose
  docker-compose.yml
Labels: chore

#1150 feat: ui improvements to lh spa on larger screen and ranking change
  packages/lighthouse-spa/package-lock.json
  packages/lighthouse-spa/package.json
  packages/lighthouse-spa/src/app/dashboard/components/property-card/property-card.component.html
  packages/lighthouse-spa/src/app/dashboard/components/property-card/property-card.component.scss
  packages/lighthouse-spa/src/app/dashboard/dashboard.gql.ts
  packages/lighthouse-spa/src/app/dashboard/dashboard.module.ts
  packages/lighthouse-spa/src/app/dashboard/dashboard.service.ts
  packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.html
  packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.scss
  packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.ts
  packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.html
  packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.scss
  packages/lighthouse-spa/src/app/leaderboard/pages/leaderboard/leaderboard.component.html
  packages/lighthouse-spa/src/app/leaderboard/pages/leaderboard/leaderboard.component.scss
  packages/lighthouse-spa/src/app/shared/components/context-selector/context-selector.component.html
  packages/lighthouse-spa/src/app/shared/components/context-selector/context-selector.component.scss
  packages/lighthouse-spa/src/app/shared/components/context-selector/context-selector.component.spec.ts
  packages/lighthouse-spa/src/app/shared/components/context-selector/context-selector.component.ts
  packages/lighthouse-spa/src/app/shared/shared.module.ts
  packages/lighthouse-spa/src/styles.scss
Labels: enhancement

#1148 Feat#1319: CouchDB config implementation in Developer Console SPA
  packages/developer-console-spa/.env.example
  packages/developer-console-spa/package-lock.json
  packages/developer-console-spa/src/App.tsx
  packages/developer-console-spa/src/assets/storage_black_24dp.svg
  packages/developer-console-spa/src/components/AppIndex.css
  packages/developer-console-spa/src/components/AppOverview.tsx
  packages/developer-console-spa/src/components/ConfigureCouchDB.tsx
  packages/developer-console-spa/src/components/ConfigureLighthouse.tsx
  packages/developer-console-spa/src/components/Sidebar.tsx
  packages/developer-console-spa/src/components/couchdb/CreateDBForm.tsx
  packages/developer-console-spa/src/types.ts
  packages/developer-console-spa/src/utils/gql-queries/app-by-appid.ts
  packages/developer-console-spa/src/utils/gql-queries/create-app-database.ts
  packages/developer-console-spa/src/utils/gql-queries/index.ts
Labels: enhancement

#1151 fix(cwe-1022): patches unsafe external link
  packages/search-spa/src/app/search/search.component.html
Labels: bug, enhancement
