Repository 1-Platform/one-platform, pull requests merged in 2021-11, with the labels that each got.

#1279 feat(1284): api-catalog-service improvements with the new
  packages/api-catalog-service/package-lock.json
  packages/api-catalog-service/package.json
  packages/api-catalog-service/src/namespace/resolver.ts
  packages/api-catalog-service/src/namespace/schema.ts
  packages/api-catalog-service/src/namespace/typedef.graphql
  packages/api-catalog-service/src/shared/cron/cron.ts
  packages/api-catalog-service/src/shared/emails/update-email-config.ts
  packages/api-catalog-service/src/shared/helpers.ts
  packages/api-catalog-service/src/shared/typedef.graphql
  packages/api-catalog-service/src/types.d.ts
Labels: enhancement

#1289 fix: opc-base chrome error and subscription variable fix
  packages/opc-base/package-lock.json
  packages/opc-base/package.json
  packages/opc-base/src/config/graphql.ts
  packages/opc-base/src/opc-provider/opc-provider.ts
Labels: bug

#1284 fix(1602): implemented stricter url validation in report generation page
  packages/lighthouse-spa/package-lock.json
  packages/lighthouse-spa/package.json
  packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.html
  packages/lighthouse-spa/src/app/playground/components/home/home.component.html
  packages/lighthouse-spa/src/app/shared/directive/url-validator.directive.spec.ts
  packages/lighthouse-spa/src/app/shared/directive/url-validator.directive.ts
  packages/lighthouse-spa/src/app/shared/shared.module.ts
Labels: bug

#1295 chore(#1294) - Remove the notification-spa from the mono-repo
  packages/notification-spa/.browserslistrc
  packages/notification-spa/.dockerignore
  packages/notification-spa/.editorconfig
  packages/notification-spa/.gitignore
  packages/notification-spa/Dockerfile
  packages/notification-spa/README.md
  packages/notification-spa/angular.json
  packages/notification-spa/e2e/protractor.conf.js
  packages/notification-spa/e2e/src/app.e2e-spec.ts
  packages/notification-spa/e2e/src/app.po.ts
  packages/notification-spa/e2e/tsconfig.json
  packages/notification-spa/jest.config.js
  packages/notification-spa/package-lock.json
  packages/notification-spa/package.json
  packages/notification-spa/set-env.ts
  packages/notification-spa/spaship.yaml
  packages/notification-spa/src/app/app-routing.module.ts
  packages/notification-spa/src/app/app.component.html
  packages/notification-spa/src/app/app.component.scss
  packages/notification-spa/src/app/app.component.spec.ts
  packages/notification-spa/src/app/app.component.ts
  packages/notification-spa/src/app/app.gql.ts
  packages/notification-spa/src/app/app.module.ts
  packages/notification-spa/src/app/app.service.ts
  packages/notification-spa/src/app/graphql.module.ts
  packages/notification-spa/src/app/helper.ts
  packages/notification-spa/src/app/index/index.component.html
  packages/notification-spa/src/app/index/index.component.scss
  packages/notification-spa/src/app/index/index.component.spec.ts
  packages/notification-spa/src/app/index/index.component.ts
  packages/notification-spa/src/app/index/spa-notifications-list/spa-notifications-list.component.html
  packages/notification-spa/src/app/index/spa-notifications-list/spa-notifications-list.component.scss
  packages/notification-spa/src/app/index/spa-notifications-list/spa-notifications-list.component.ts
  packages/notification-spa/src/app/manage-notification/manage-notification.component.html
  packages/notification-spa/src/app/manage-notification/manage-notification.component.scss
  packages/notification-spa/src/app/manage-notification/manage-notification.component.spec.ts
  packages/notification-spa/src/app/manage-notification/manage-notification.component.ts
  packages/notification-spa/src/app/mocks/notificationItems.mock.ts
  packages/notification-spa/src/app/mocks/user.mock.ts
  packages/notification-spa/src/app/module.d.ts
  packages/notification-spa/src/app/side-panel/side-panel.component.html
  packages/notification-spa/src/app/side-panel/side-panel.component.scss
  packages/notification-spa/src/app/side-panel/side-panel.component.spec.ts
  packages/notification-spa/src/app/side-panel/side-panel.component.ts
  packages/notification-spa/src/app/type.d.ts
  packages/notification-spa/src/assets/.gitkeep
  packages/notification-spa/src/environments/environment.prod.ts
  packages/notification-spa/src/environments/environment.ts
  packages/notification-spa/src/global.d.ts
  packages/notification-spa/src/index.html
  packages/notification-spa/src/main.ts
  packages/notification-spa/src/polyfills.ts
  packages/notification-spa/src/setup-jest.ts
  packages/notification-spa/src/styles.scss
  packages/notification-spa/src/test-config.helper.ts
  packages/notification-spa/tsconfig.app.json
  packages/notification-spa/tsconfig.base.json
  packages/notification-spa/tsconfig.json
  packages/notification-spa/tsconfig.spec.json
  packages/notification-spa/tslint.json
Labels: chore

#1293 fix(1611,1616): Lighthouse - fixed loader on empty branches and audit upload fix
  packages/lighthouse-spa/package-lock.json
  packages/lighthouse-spa/package.json
  packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.html
  packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.html
  packages/lighthouse-spa/src/app/dashboard/pipes/timeline-score-formater.pipe.ts
  packages/lighthouse-spa/src/app/dashboard/types.d.ts
  packages/lighthouse-spa/src/app/graphql.module.ts
  packages/lighthouse-spa/src/app/playground/components/home/home.component.html
  packages/lighthouse-spa/src/app/playground/components/home/home.component.spec.ts
  packages/lighthouse-spa/src/app/playground/components/home/home.component.ts
  packages/lighthouse-spa/src/app/playground/playground.gql.ts
  packages/lighthouse-spa/src/app/playground/playground.module.ts
  packages/lighthouse-spa/src/app/playground/playground.service.ts
  packages/lighthouse-spa/src/app/shared/components/form-error-message/form-error-message.component.html
  packages/lighthouse-spa/src/app/shared/components/form-error-message/form-error-message.component.scss
  packages/lighthouse-spa/src/app/shared/components/form-error-message/form-error-message.component.spec.ts
  packages/lighthouse-spa/src/app/shared/components/form-error-message/form-error-message.component.ts
  packages/lighthouse-spa/src/app/shared/shared.module.ts
Labels: bug

#1298 Fix#1610: Adding validations for only white spaces in the fields.
  packages/developer-console-spa/package-lock.json
  packages/developer-console-spa/package.json
  packages/developer-console-spa/src/components/couchdb/AddUserForm.tsx
  packages/developer-console-spa/src/components/couchdb/CreateDBForm.tsx
  packages/developer-console-spa/src/components/lighthouse/CreateProjectForm.tsx
Labels: bug

#1299 feat(1554): applied source integrity to all third party scripts
  packages/api-catalog-spa/public/index.html
  packages/component-catalog-spa/public/index.html
  packages/developer-console-spa/public/index.html
  packages/feedback-spa/public/index.html
  packages/home-spa/src/_includes/layout/base.njk
  packages/home-spa/src/_includes/partials/footer.njk
  packages/home-spa/src/_includes/partials/header.njk
  packages/lighthouse-spa/src/index.html
  packages/search-spa/src/index.html
  packages/user-group-spa/public/index.html
Labels: enhancement

#1301 feat: opc-base changed to warning on mutating config values
  packages/opc-base/docs/opc-base.md
  packages/opc-base/package-lock.json
  packages/opc-base/package.json
  packages/opc-base/src/opc-base/opc-base.ts
  packages/opc-base/src/opc-base/types.ts
Labels: enhancement

#1302 hotfix: fixed incorrect spaship url path
  packages/api-catalog-spa/package-lock.json
  packages/api-catalog-spa/package.json
  packages/api-catalog-spa/spaship.yaml
  packages/api-catalog-spa/src/components/ReadMore/ReadMore.tsx
  packages/api-catalog-spa/src/pages/GqlPlaygroundPage/GqlPlaygroundPage.tsx
Labels: bug

#1315 fix(1691): lighthouse - fixed leaderboard cache policy issue
  packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.ts
  packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.ts
  packages/lighthouse-spa/src/app/leaderboard/leaderboard.service.ts
  packages/lighthouse-spa/src/app/leaderboard/pages/leaderboard/leaderboard.component.ts
  packages/lighthouse-spa/src/app/playground/components/home/home.component.ts
Labels: bug

#1305 feat(apps): Create mutation for transfer ownership
  packages/apps-service/Dockerfile
  packages/apps-service/package-lock.json
  packages/apps-service/package.json
  packages/apps-service/src/@types/apps/index.d.ts
  packages/apps-service/src/index.ts
  packages/apps-service/src/lib/logger.ts
  packages/apps-service/src/modules/apps/model.ts
  packages/apps-service/src/modules/apps/resolver.ts
  packages/apps-service/src/modules/apps/schema.gql.ts
  packages/apps-service/src/services/couchdb.ts
  packages/apps-service/src/services/user-group.ts
  packages/apps-service/src/setup/database.ts
  packages/apps-service/src/utils/apps-helper.ts
  packages/apps-service/src/utils/gql-queries/getUser.ts
  packages/apps-service/src/utils/unique-id-from-path.ts
Labels: enhancement, chore

#1316 feat(1692): api-catalog-spa: qa and user feedback changes
  packages/api-catalog-spa/README.md
  packages/api-catalog-spa/package-lock.json
  packages/api-catalog-spa/package.json
  packages/api-catalog-spa/src/index.tsx
  packages/api-catalog-spa/src/layouts/AppLayout/AppLayout.tsx
  packages/api-catalog-spa/src/layouts/AppLayout/appLayout.module.scss
  packages/api-catalog-spa/src/layouts/AppLayout/components/Footer/Footer.tsx
  packages/api-catalog-spa/src/pages/APIListPage/apiListPage.helper.ts
  packages/api-catalog-spa/src/pages/APIListPage/components/ApiDetailsCard/ApiDetailsCard.tsx
  packages/api-catalog-spa/src/pages/ApiCUDPage/ApiCUDPage.tsx
  packages/api-catalog-spa/src/pages/ApiCUDPage/components/EnvironmentFormSection/EnvironmentFormSection.tsx
  packages/api-catalog-spa/src/pages/ApiDescriptionPage/components/ApiEnvironmentSection/ApiEnvironmentSection.tsx
  packages/api-catalog-spa/src/pages/HomePage/HomePage.tsx
  packages/api-catalog-spa/src/pages/HomePage/components/SearchBar/SearchBar.tsx
  packages/api-catalog-spa/src/pages/HomePage/components/SearchBar/index.tsx
  packages/api-catalog-spa/src/pages/HomePage/components/SearchBar/searchBar.module.scss
  packages/api-catalog-spa/src/pages/HomePage/homePage.module.scss
  packages/api-catalog-spa/src/pages/VoyagerToolPage/VoyagerToolPage.tsx
  packages/api-catalog-spa/src/utils/errorMessages.ts
  packages/api-catalog-spa/src/utils/index.ts
Labels: enhancement
