Repository 1-Platform/one-platform, pull requests merged in 2021-12, with the labels that each got.

#1317 add api catalog test #test(ONEPLAT-1698)
  e2e/integration/apicatalogtests.js
Labels: bug, enhancement

#1322 modifications in existing test test(ONEPLAT-1702)
  e2e/integration/apicatalogtests.js
  e2e/integration/devconsoletests.js
  e2e/integration/lighthousetests.js
  e2e/integration/searchtests.js
Labels: test-automation

#1320 hotfix: doc spa moved web components to brower only and added .env.ex…
  packages/documentation-spa/.env.example
  packages/documentation-spa/src/theme/Layout/index.jsx
Labels: bug

#1326 changed ssi tests ONEPLAT-1709
  e2e/integration/ssitests.js
Labels: test-automation

#1330 test for new test cases for api catalog and added wait in search test(ONEPLAT-1713)
  e2e/integration/apicatalogtests.js
  e2e/integration/searchtests.js
Labels: test-automation

#1329 feat(1668): adopted sentry to OP SPAs
  packages/api-catalog-spa/.env.example
  packages/api-catalog-spa/package-lock.json
  packages/api-catalog-spa/package.json
  packages/api-catalog-spa/src/index.tsx
  packages/component-catalog-spa/.env.example
  packages/component-catalog-spa/package-lock.json
  packages/component-catalog-spa/package.json
  packages/component-catalog-spa/src/index.jsx
  packages/developer-console-spa/.env.example
  packages/developer-console-spa/package-lock.json
  packages/developer-console-spa/package.json
  packages/developer-console-spa/src/index.tsx
  packages/documentation-spa/.env.example
  packages/documentation-spa/package-lock.json
  packages/documentation-spa/package.json
  packages/documentation-spa/src/theme/Layout/index.jsx
  packages/feedback-spa/.env.example
  packages/feedback-spa/package-lock.json
  packages/feedback-spa/package.json
  packages/feedback-spa/src/main.js
  packages/home-spa/.env.example
  packages/home-spa/package.json
  packages/home-spa/src/_data/env.js
  packages/home-spa/src/_includes/partials/header.njk
  packages/lighthouse-spa/package-lock.json
  packages/lighthouse-spa/package.json
  packages/lighthouse-spa/set-env.ts
  packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.ts
  packages/lighthouse-spa/src/environments/environment.prod.ts
  packages/lighthouse-spa/src/environments/environment.ts
  packages/lighthouse-spa/src/main.ts
  packages/lighthouse-spa/tsconfig.json
  packages/search-spa/package-lock.json
  packages/search-spa/package.json
  packages/search-spa/set-env.ts
  packages/search-spa/src/environments/environment.prod.ts
  packages/search-spa/src/environments/environment.ts
  packages/search-spa/src/main.ts
  packages/search-spa/tsconfig.app.json
  packages/search-spa/tsconfig.base.json
  packages/user-group-spa/.env.example
  packages/user-group-spa/src/index.js
Labels: enhancement

#1332 hotfix: fixed angular spa env sentry dsn as string undefined
  packages/lighthouse-spa/set-env.ts
  packages/lighthouse-spa/src/environments/environment.prod.ts
  packages/lighthouse-spa/src/environments/environment.ts
  packages/search-spa/set-env.ts
  packages/search-spa/src/environments/environment.prod.ts
  packages/search-spa/src/environments/environment.ts
Labels: bug

#1335 feat: reverse-proxy implemented no-cors proxy for api catalog
  packages/reverse-proxy-service/package-lock.json
  packages/reverse-proxy-service/package.json
  packages/reverse-proxy-service/src/app.ts
  packages/reverse-proxy-service/src/no-cors-proxy/index.ts
  packages/reverse-proxy-service/src/no-cors-proxy/resolver.ts
Labels: enhancement

#1338 feat:api-catalog-spa fixed cors error for swagger
  packages/api-catalog-spa/.env.example
  packages/api-catalog-spa/package-lock.json
  packages/api-catalog-spa/package.json
  packages/api-catalog-spa/src/context/RecentVisitContext/RecentVisitContext.tsx
  packages/api-catalog-spa/src/context/RecentVisitContext/types.ts
  packages/api-catalog-spa/src/pages/ApiCUDPage/ApiCUDPage.tsx
  packages/api-catalog-spa/src/pages/ApiCUDPage/components/EnvHeaderFormSection/EnvHeaderFormSection.tsx
  packages/api-catalog-spa/src/pages/ApiDescriptionPage/ApiDescriptionPage.tsx
  packages/api-catalog-spa/src/pages/GqlPlaygroundPage/GqlPlaygroundPage.tsx
  packages/api-catalog-spa/src/pages/SwaggerToolPage/SwaggerToolPage.tsx
  packages/api-catalog-spa/src/pages/VoyagerToolPage/VoyagerToolPage.tsx
Labels: enhancement

#1334 test for search,edit and delete of apis(ONEPLAT-1724)
  e2e/integration/apicatalogtests.js
  e2e/integration/feedbacktests.js
  e2e/integration/searchtests.js
  package.json
Labels: test-automation

#1343 apicatalog test and chromium browser test (ONEPLAT-1702)
  cypress.json
  e2e/integration/apicatalogtests.js
  package.json
Labels: test-automation

#1296 feat: LH - removed property-manager from microservice
  packages/lighthouse-service/.eslintrc.js
  packages/lighthouse-service/package-lock.json
  packages/lighthouse-service/package.json
  packages/lighthouse-service/service.ts
  packages/lighthouse-service/src/audit-manager/resolver.ts
  packages/lighthouse-service/src/audit-manager/typedef.graphql
  packages/lighthouse-service/src/helpers.ts
  packages/lighthouse-service/src/lighthouse-db-manager/lighthouse-db-manager.ts
  packages/lighthouse-service/src/lighthouse-db-manager/sequelize.ts
  packages/lighthouse-service/src/lighthouse-spa-config/helpers.ts
  packages/lighthouse-service/src/lighthouse-spa-config/resolver.ts
  packages/lighthouse-service/src/property-manager/helpers.ts
  packages/lighthouse-service/src/property-manager/resolver.ts
  packages/lighthouse-service/src/property-manager/schema.ts
  packages/lighthouse-service/src/property-manager/typedef.graphql
Labels: enhancement

#1337 feat(1678): implemented test cases for opc-base package
  packages/opc-base/.gitignore
  packages/opc-base/README.md
  packages/opc-base/dev/config.es.example.js
  packages/opc-base/dev/es.html
  packages/opc-base/jest.config.js
  packages/opc-base/package-lock.json
  packages/opc-base/package.json
  packages/opc-base/rollup.config.js
  packages/opc-base/src/components/opc-drawer-footer/opc-drawer-footer.test.ts
  packages/opc-base/src/components/opc-loader/opc-loader.test.ts
  packages/opc-base/src/components/opc-loader/opc-loader.ts
  packages/opc-base/src/components/opc-menu-drawer/opc-avatar/opc-avatar.test.ts
  packages/opc-base/src/components/opc-notification-drawer/opc-filter-chip/opc-filter-chip.test.ts
  packages/opc-base/src/components/opc-toast/opc-toast.test.ts
  packages/opc-base/src/components/opc-toast/opc-toast.ts
  packages/opc-base/src/opc-base/opc-base.test.ts
  packages/opc-base/src/opc-provider/opc-provider.test.ts
  packages/opc-base/src/opc-provider/opc-provider.ts
  packages/opc-base/test/opc-provider.js
  packages/opc-base/tsconfig.json
  packages/opc-base/web-test-runner.config.js
Labels: enhancement, test-automation

#1333 Chore/#1306 - Add multiple component libraries in component catalog SPA
  packages/component-catalog-spa/README.md
  packages/component-catalog-spa/package-lock.json
  packages/component-catalog-spa/package.json
  packages/component-catalog-spa/public/favicon.ico
  packages/component-catalog-spa/public/index.html
  packages/component-catalog-spa/src/App.jsx
  packages/component-catalog-spa/src/App.scss
  packages/component-catalog-spa/src/Components/Description.jsx
  packages/component-catalog-spa/src/Components/Description.scss
  packages/component-catalog-spa/src/Components/Main.jsx
  packages/component-catalog-spa/src/Components/Main.scss
  packages/component-catalog-spa/src/Components/Navbar.jsx
  packages/component-catalog-spa/src/Configs/component-libraries.js
  packages/component-catalog-spa/src/Configs/footer.js
  packages/component-catalog-spa/src/Configs/repositoryConfig.js
  packages/component-catalog-spa/src/Hooks/useFetchReadme.js
  packages/component-catalog-spa/src/Pages/Home.jsx
  packages/component-catalog-spa/src/assets/images/druplicon-vector.svg
  packages/component-catalog-spa/src/index.jsx
  packages/component-catalog-spa/src/index.scss
  packages/component-catalog-spa/src/pages/Main.jsx
  packages/component-catalog-spa/src/pages/Main.scss
Labels: chore

#1347 fix(ONEPLAT/1735): Changed the link for webrh components
  packages/component-catalog-spa/package-lock.json
  packages/component-catalog-spa/src/Components/Main.jsx
  packages/component-catalog-spa/src/Configs/component-libraries.js
Labels: chore

#1345 search test fixes (ONEPLAT-1707)
  e2e/integration/searchtests.js
Labels: test-automation

#1348 hotfix: comment out sentry env in .env.example to avoid build error
  packages/component-catalog-spa/.env.example
  packages/developer-console-spa/.env.example
  packages/documentation-spa/.env.example
  packages/feedback-spa/.env.example
  packages/home-spa/.env.example
  packages/user-group-spa/.env.example
Labels: bug

#1349 hotfix: search-spa migrated opc-nav to latest
  packages/search-spa/package-lock.json
  packages/search-spa/package.json
Labels: enhancement

#1351 fix(1739): doc-spa - fixed broken links in footer
  packages/documentation-spa/docusaurus.config.js
  packages/documentation-spa/package-lock.json
  packages/documentation-spa/package.json
Labels: bug

#1350 feat(1683): lighthouse spa - implemented unit test cases
  packages/lighthouse-spa/babel.config.js
  packages/lighthouse-spa/jest.config.js
  packages/lighthouse-spa/package-lock.json
  packages/lighthouse-spa/src/app/dashboard/dashboard.service.spec.ts
  packages/lighthouse-spa/src/app/dashboard/mock-dashboard.ts
  packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.spec.ts
  packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.spec.ts
  packages/lighthouse-spa/src/app/dashboard/pipes/timeline-score-formater.pipe.spec.ts
  packages/lighthouse-spa/src/app/dashboard/pipes/timeline-score-formater.pipe.ts
  packages/lighthouse-spa/src/app/leaderboard/components/leaderboard-card/leaderboard-card.component.spec.ts
  packages/lighthouse-spa/src/app/leaderboard/leaderboard.service.spec.ts
  packages/lighthouse-spa/src/app/leaderboard/leaderboard.service.ts
  packages/lighthouse-spa/src/app/leaderboard/mock-leaderboard.ts
  packages/lighthouse-spa/src/app/leaderboard/pages/leaderboard/leaderboard.component.spec.ts
  packages/lighthouse-spa/src/app/leaderboard/pages/leaderboard/leaderboard.component.ts
  packages/lighthouse-spa/src/app/leaderboard/pipes/leaderboard-label-formater.pipe.spec.ts
  packages/lighthouse-spa/src/app/playground/components/home/home.component.spec.ts
  packages/lighthouse-spa/src/app/playground/components/home/home.component.ts
  packages/lighthouse-spa/src/app/playground/mock-playground.ts
  packages/lighthouse-spa/src/app/playground/playground.gql.ts
  packages/lighthouse-spa/src/app/playground/playground.service.spec.ts
  packages/lighthouse-spa/src/app/playground/playground.service.ts
  packages/lighthouse-spa/src/app/shared/components/avatar/avatar.component.spec.ts
  packages/lighthouse-spa/src/app/shared/components/context-selector/context-selector.component.html
  packages/lighthouse-spa/src/app/shared/components/context-selector/context-selector.component.spec.ts
  packages/lighthouse-spa/src/app/shared/components/empty-state/empty-state.component.spec.ts
  packages/lighthouse-spa/src/app/shared/components/form-error-message/form-error-message.component.spec.ts
  packages/lighthouse-spa/src/app/shared/components/loader/loader.component.spec.ts
  packages/lighthouse-spa/src/app/shared/components/outlined-pie-graph/outlined-pie-graph.component.spec.ts
  packages/lighthouse-spa/src/app/shared/directive/url-validator.directive.spec.ts
  packages/lighthouse-spa/src/app/shared/pipes/filter-list.pipe.spec.ts
  packages/lighthouse-spa/src/app/shared/pipes/lhscore-label-formater.pipe.spec.ts
Labels: test-automation

#1353 fix(#1352) - Favicon missing and the designation of employees needs revamp and the oneplatform link is not there
  packages/home-spa/.eleventy.js
  packages/home-spa/package-lock.json
  packages/home-spa/package.json
  packages/home-spa/src/_includes/partials/footer.njk
  packages/home-spa/src/contact-us.njk
  packages/home-spa/src/favicon.ico
Labels: chore

#1354 chore:1677 - Updated the test cases for the api-catalog microservice
  packages/api-catalog-service/Dockerfile
  packages/api-catalog-service/package-lock.json
  packages/api-catalog-service/package.json
  packages/api-catalog-service/src/e2e/api-catalog.spec.ts
  packages/api-catalog-service/src/e2e/mock.js
Labels: chore
