Repository 1-Platform/one-platform, pull requests merged in 2021-07, with the labels that each got.

#1009 Feat: #1202: Updating user service documentation
  packages/documentation-spa/docs/microservices/user-groups/user-groups-service.md
Labels: documentation, small pr

#1014 docs(api-gateway): Creates documentation for API Gateway
  packages/documentation-spa/docs/microservices/api-gateway/api-gateway.md
  packages/documentation-spa/sidebars.js
Labels: documentation

#1020 fix(1302): fixed type conflicts with apps service and lighthouse service
  packages/lighthouse-service/src/audit-manager/resolver.ts
  packages/lighthouse-service/src/audit-manager/typedef.graphql
  packages/lighthouse-service/src/property-manager/resolver.ts
  packages/lighthouse-service/src/property-manager/typedef.graphql
  packages/lighthouse-spa/src/app/app.gql.ts
  packages/lighthouse-spa/src/app/app.service.ts
  packages/lighthouse-spa/src/app/dashboard/dashboard.gql.ts
  packages/lighthouse-spa/src/app/dashboard/dashboard.service.ts
  packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.ts
  packages/lighthouse-spa/src/app/dashboard/pages/dashboard/dashboard.component.ts
  packages/lighthouse-spa/src/app/home/components/home/home.component.ts
Labels: bug

#1018 (chore:logging) - Removed unused libraries and variables from codebase
  packages/user-group-service/package-lock.json
  packages/user-group-service/package.json
  packages/user-group-service/service.ts
  packages/user-group-service/src/users/cron.ts
Labels: chore

#1016 Feat#1287: Improving the search index API & API helper modifications in Feedback service
  packages/feedback-service/src/helpers.ts
  packages/feedback-service/src/resolver.ts
  packages/search-service/src/search-config/helpers.ts
  packages/search-service/src/search-config/resolver.ts
  packages/search-service/src/search-config/typedef.graphql
  packages/search-service/src/search-mapping/helpers.ts
  packages/search-service/src/search-mapping/resolver.ts
  packages/search-service/src/search-mapping/typedef.graphql
Labels: enhancement

#1017 (docs:1209) - Included Documentation of Lighthouse Microservice and Spa
  packages/documentation-spa/docs/apps/internal/lighthouse/home.png
  packages/documentation-spa/docs/apps/internal/lighthouse/lighthouse-spa.md
  packages/documentation-spa/docs/microservices/lighthouse-service/lighthouse-service.md
  packages/documentation-spa/sidebars.js
Labels: documentation

#967 Dependency update for all the renovate changes
  cli/generator-op-microservice/package-lock.json
  cli/generator-op-microservice/package.json
  package-lock.json
  package.json
  packages/api-gateway-service/package.json
  packages/apps-service/package.json
  packages/documentation-spa/package-lock.json
  packages/feedback-service/package-lock.json
  packages/feedback-service/package.json
  packages/feedback-spa/package.json
  packages/feedback-spa/yarn.lock
  packages/home-spa/package-lock.json
  packages/home-spa/package.json
  packages/notification-spa/package-lock.json
  packages/notification-spa/package.json
  packages/notifications-service/package-lock.json
  packages/notifications-service/package.json
  packages/notifications-service/src/broadcaster.ts
  packages/notifications-service/src/helpers.ts
  packages/search-service/package-lock.json
  packages/search-service/package.json
  packages/search-spa/package-lock.json
  packages/search-spa/package.json
  packages/ssi-service/package-lock.json
  packages/ssi-service/package.json
  packages/ssi-service/src/default.html
  packages/ssi-service/src/feedback.slim.html
  packages/user-group-service/package.json
  packages/user-group-spa/package-lock.json
Labels: dependencies

#1025 Fixes broken links in documentation spa
  packages/documentation-spa/docs/apps/internal/feedback/feedback-spa.md
  packages/documentation-spa/docs/faqs.md
  packages/documentation-spa/docs/microservices/api-gateway/api-gateway.md
Labels: bug

#1023 fix: fixed links of lighthouse-spa
  packages/lighthouse-spa/src/app/shared/layouts/app-layout/app-layout.component.html
  packages/lighthouse-spa/src/app/shared/layouts/app-layout/app-layout.component.scss
  packages/lighthouse-spa/src/app/shared/layouts/app-layout/app-layout.component.ts
Labels: bug

#1013 (docs/1204) - Updated the APIs and documentation for Search Microservice
  packages/documentation-spa/blog/2021-07-13-state-of-one-platform-mayjun-2021.md
  packages/documentation-spa/docs/microservices/search/search-service.md
Labels: documentation

#1027 feat(apps-service): Adds support for id in findApps and app query
  packages/apps-service/src/modules/apps/model.ts
  packages/apps-service/src/modules/apps/resolver.ts
  packages/apps-service/src/modules/apps/schema.gql.ts
  packages/apps-service/src/modules/microservices/resolver.ts
  packages/apps-service/src/modules/microservices/schema.gql.ts
Labels: enhancement

#1029 Feat#1263: Index apps service data to search microservice
  packages/apps-service/.env.example
  packages/apps-service/src/modules/apps/resolver.ts
  packages/apps-service/src/utils/apps-helper.ts
  packages/search-service/src/search-mapping/cron.ts
Labels: enhancement

#1004 feat(dev-console): Adds AppSettings page to modify apps
  packages/developer-console-spa/src/App.tsx
  packages/developer-console-spa/src/components/AddAppForm.tsx
  packages/developer-console-spa/src/components/AppIndex.tsx
  packages/developer-console-spa/src/components/AppOverview.tsx
  packages/developer-console-spa/src/components/AppSettings.tsx
  packages/developer-console-spa/src/components/Sidebar.tsx
  packages/developer-console-spa/src/context/AppContext.tsx
  packages/developer-console-spa/src/hooks/useAppAPI.ts
  packages/developer-console-spa/src/react-app-env.d.ts
  packages/developer-console-spa/src/services/app.ts
  packages/developer-console-spa/src/utils/gql-queries/delete-app.ts
  packages/developer-console-spa/src/utils/gql-queries/index.ts
  packages/developer-console-spa/src/utils/gql-queries/update-app.ts
Labels: enhancement

#1030 fix(#1024) - Deploy to One Platform Button enhancements
  packages/home-spa/.env.example
  packages/home-spa/README.md
  packages/home-spa/src/home/home.html
  packages/home-spa/src/home/home.js
  packages/home-spa/src/res/static/microservices.json
  packages/home-spa/src/service/service.js
  packages/home-spa/webpack.config.js
Labels: chore

#1031 fix(apps-service): Handled null value for id in apps service
  packages/apps-service/src/modules/apps/resolver.ts
  packages/apps-service/src/modules/microservices/resolver.ts
Labels: bug

#1033 fix(#1032) - Link error for apps on SSI app drawer
  packages/ssi-service/package-lock.json
  packages/ssi-service/src/nav/nav.js
Labels: bug

#1015 (feat:1191) - Included the Configs for the lighthouse ci for One Platform
  .gitignore
  packages/developer-console-spa/lighthouserc.js
  packages/developer-console-spa/package-lock.json
  packages/developer-console-spa/package.json
  packages/documentation-spa/lighthouserc.js
  packages/documentation-spa/package-lock.json
  packages/feedback-spa/lighthouserc.js
  packages/feedback-spa/package.json
  packages/home-spa/lighthouserc.js
  packages/home-spa/package-lock.json
  packages/home-spa/package.json
  packages/lighthouse-spa/lighthouserc.js
  packages/lighthouse-spa/package-lock.json
  packages/lighthouse-spa/package.json
  packages/search-spa/lighthouserc.js
  packages/search-spa/package-lock.json
  packages/search-spa/package.json
  packages/user-group-spa/lighthouserc.js
  packages/user-group-spa/package-lock.json
  packages/user-group-spa/package.json
  puppeteerScript.js
Labels: enhancement

#1034 feat(gh-actions): Updates github actions for the release branch
  .github/workflows/build-api-gateway.yml
  .github/workflows/build-apps-service.yml
  .github/workflows/build-feedback-service.yml
  .github/workflows/build-notifications-service.yml
  .github/workflows/build-search-service.yml
  .github/workflows/build-user-group-service.yml
Labels: enhancement

#1037 Hotfix: ui improvment and fixed broken link
  packages/lighthouse-spa/src/app/app.component.html
  packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.html
  packages/lighthouse-spa/src/app/dashboard/pages/dashboard/dashboard.component.html
  packages/lighthouse-spa/src/app/dashboard/pages/dashboard/dashboard.component.ts
  packages/lighthouse-spa/src/app/shared/layouts/app-layout/app-layout.component.html
  packages/lighthouse-spa/src/app/shared/layouts/app-layout/app-layout.component.scss
  packages/lighthouse-spa/src/app/shared/shared.module.ts
  packages/lighthouse-spa/src/styles.scss
Labels: enhancement

#1039 (Fix:lh-image) - Included non-root permission for the image
  packages/lighthouse-service/Dockerfile
Labels: dependencies

#1036 fix(ghactions): Adds workflow_dispatch inputs for ghactions
  .github/workflows/build-api-gateway.yml
  .github/workflows/build-apps-service.yml
  .github/workflows/build-feedback-service.yml
  .github/workflows/build-lighthouse-service.yml
  .github/workflows/build-notifications-service.yml
  .github/workflows/build-search-service.yml
  .github/workflows/build-user-group-service.yml
Labels: chore

#1045 Updating env example for Search & User Group services
  packages/search-service/.env.example
  packages/user-group-service/.env.example
Labels: small pr

#1052 chore(user-group-spa) Adds .env for config management
  packages/user-group-spa/.env.example
  packages/user-group-spa/public/config.js
  packages/user-group-spa/src/services/FetchClient.js
Labels: chore

#1053 fix(user-group-spa): Removes unused variables and fixes build warnings
  packages/user-group-spa/src/App.jsx
  packages/user-group-spa/src/components/Form.jsx
  packages/user-group-spa/src/components/Group.jsx
  packages/user-group-spa/src/components/Home.jsx
  packages/user-group-spa/src/components/NotFound.jsx
  packages/user-group-spa/src/components/User.jsx
  packages/user-group-spa/src/services/GroupsAPI.js
Labels: bug
