Repository 1-Platform/one-platform, pull requests merged in 2021-06, with the labels that each got.

#979 fix(ssi): Temporary fix for the blank app drawer issue
  packages/ssi-service/src/nav/api.js
  packages/ssi-service/src/nav/nav.js
Labels: bug

#974 (feat:1152) - Lighthouse SPA Interface for testing web properties
  packages/lighthouse-spa/.browserslistrc
  packages/lighthouse-spa/.editorconfig
  packages/lighthouse-spa/.gitignore
  packages/lighthouse-spa/README.md
  packages/lighthouse-spa/angular.json
  packages/lighthouse-spa/e2e/protractor.conf.js
  packages/lighthouse-spa/e2e/src/app.e2e-spec.ts
  packages/lighthouse-spa/e2e/src/app.po.ts
  packages/lighthouse-spa/e2e/tsconfig.json
  packages/lighthouse-spa/jest.config.js
  packages/lighthouse-spa/karma.conf.js
  packages/lighthouse-spa/package-lock.json
  packages/lighthouse-spa/package.json
  packages/lighthouse-spa/set-env.ts
  packages/lighthouse-spa/src/app/app-routing.module.ts
  packages/lighthouse-spa/src/app/app.component.html
  packages/lighthouse-spa/src/app/app.component.scss
  packages/lighthouse-spa/src/app/app.component.spec.ts
  packages/lighthouse-spa/src/app/app.component.ts
  packages/lighthouse-spa/src/app/app.gql.ts
  packages/lighthouse-spa/src/app/app.module.ts
  packages/lighthouse-spa/src/app/app.service.spec.ts
  packages/lighthouse-spa/src/app/app.service.ts
  packages/lighthouse-spa/src/app/graphql.module.ts
  packages/lighthouse-spa/src/app/home/home.component.html
  packages/lighthouse-spa/src/app/home/home.component.scss
  packages/lighthouse-spa/src/app/home/home.component.spec.ts
  packages/lighthouse-spa/src/app/home/home.component.ts
  packages/lighthouse-spa/src/assets/.gitkeep
  packages/lighthouse-spa/src/environments/environment.prod.ts
  packages/lighthouse-spa/src/environments/environment.ts
  packages/lighthouse-spa/src/favicon.ico
  packages/lighthouse-spa/src/index.html
  packages/lighthouse-spa/src/main.ts
  packages/lighthouse-spa/src/polyfills.ts
  packages/lighthouse-spa/src/setup-jest.ts
  packages/lighthouse-spa/src/spaship.yaml
  packages/lighthouse-spa/src/styles.scss
  packages/lighthouse-spa/src/types.d.ts
  packages/lighthouse-spa/tsconfig.app.json
  packages/lighthouse-spa/tsconfig.json
  packages/lighthouse-spa/tsconfig.spec.json
  packages/lighthouse-spa/tslint.json
Labels: enhancement

#973 (feat:1153) - Lighthouse Microservice for One Platform
  packages/lighthouse-service/.dockerignore
  packages/lighthouse-service/.env.example
  packages/lighthouse-service/.gitignore
  packages/lighthouse-service/Dockerfile
  packages/lighthouse-service/README.md
  packages/lighthouse-service/jest.config.js
  packages/lighthouse-service/package-lock.json
  packages/lighthouse-service/package.json
  packages/lighthouse-service/service.ts
  packages/lighthouse-service/src/e2e/audit-manager.spec.ts
  packages/lighthouse-service/src/e2e/mock.json
  packages/lighthouse-service/src/helpers.ts
  packages/lighthouse-service/src/lighthouse-audit-manager/resolver.ts
  packages/lighthouse-service/src/lighthouse-audit-manager/typedef.graphql
  packages/lighthouse-service/src/types.d.ts
  packages/lighthouse-service/tsconfig.json
  packages/lighthouse-service/tslint.json
  packages/lighthouse-service/webpack.common.js
  packages/lighthouse-service/webpack.dev.js
  packages/lighthouse-service/webpack.prod.js
Labels: enhancement

#982 feat(dev-console): Implements dev console index and app shell pages
  docker-compose.yml
  packages/developer-console-spa/.env.example
  packages/developer-console-spa/.gitignore
  packages/developer-console-spa/README.md
  packages/developer-console-spa/package-lock.json
  packages/developer-console-spa/package.json
  packages/developer-console-spa/public/chrome.html
  packages/developer-console-spa/public/favicon.ico
  packages/developer-console-spa/public/index.html
  packages/developer-console-spa/public/logo192.png
  packages/developer-console-spa/public/logo512.png
  packages/developer-console-spa/public/manifest.json
  packages/developer-console-spa/public/robots.txt
  packages/developer-console-spa/spaship.yaml
  packages/developer-console-spa/src/App.css
  packages/developer-console-spa/src/App.spec.tsx
  packages/developer-console-spa/src/App.tsx
  packages/developer-console-spa/src/components/AddAppForm.tsx
  packages/developer-console-spa/src/components/AppCard.tsx
  packages/developer-console-spa/src/components/AppConsoleShell.tsx
  packages/developer-console-spa/src/components/AppIndex.css
  packages/developer-console-spa/src/components/AppIndex.spec.tsx
  packages/developer-console-spa/src/components/AppIndex.tsx
  packages/developer-console-spa/src/components/AppOverview.css
  packages/developer-console-spa/src/components/AppOverview.tsx
  packages/developer-console-spa/src/components/ConfigureDatabase.tsx
  packages/developer-console-spa/src/components/ConfigureFeedback.tsx
  packages/developer-console-spa/src/components/ConfigureSSI.tsx
  packages/developer-console-spa/src/components/Loader.tsx
  packages/developer-console-spa/src/components/NotFound.tsx
  packages/developer-console-spa/src/components/Sidebar.css
  packages/developer-console-spa/src/components/Sidebar.tsx
  packages/developer-console-spa/src/components/UnderDevelopment.tsx
  packages/developer-console-spa/src/context/AppContext.tsx
  packages/developer-console-spa/src/declarations.d.ts
  packages/developer-console-spa/src/hooks/useAppAPI.ts
  packages/developer-console-spa/src/hooks/useMyAppsAPI.ts
  packages/developer-console-spa/src/index.css
  packages/developer-console-spa/src/index.tsx
  packages/developer-console-spa/src/react-app-env.d.ts
  packages/developer-console-spa/src/reportWebVitals.ts
  packages/developer-console-spa/src/setupTests.ts
  packages/developer-console-spa/src/utils/gql-queries/app-by-appid.ts
  packages/developer-console-spa/src/utils/gql-queries/index.ts
  packages/developer-console-spa/src/utils/gql-queries/my-apps.ts
  packages/developer-console-spa/src/utils/gql-queries/new-app.ts
  packages/developer-console-spa/src/utils/gqlClient.ts
  packages/developer-console-spa/tsconfig.json
Labels: enhancement

#993 fix(apps-service): Fixes myApps query and adds resolvers for service
  packages/apps-service/src/@types/apps/index.d.ts
  packages/apps-service/src/@types/microservices/index.d.ts
  packages/apps-service/src/index.ts
  packages/apps-service/src/modules/apps/model.ts
  packages/apps-service/src/modules/apps/resolver.ts
  packages/apps-service/src/modules/apps/schema.gql.ts
  packages/apps-service/src/modules/microservices/index.ts
  packages/apps-service/src/modules/microservices/model.ts
  packages/apps-service/src/modules/microservices/resolver.ts
  packages/apps-service/src/modules/microservices/schema.gql.ts
  packages/apps-service/src/utils/unique-id-from-path.ts
Labels: bug, enhancement

#978 (docs:#1203) - Updates the documentation for feedback spa & microservice.
  packages/documentation-spa/docs/apps/internal/feedback/details.svg
  packages/documentation-spa/docs/apps/internal/feedback/feedback-popout.svg
  packages/documentation-spa/docs/apps/internal/feedback/feedback-spa-home.svg
  packages/documentation-spa/docs/apps/internal/feedback/feedback-spa.md
  packages/documentation-spa/docs/apps/internal/feedback/home.svg
  packages/documentation-spa/docs/microservices/feedback/feedback-service.md
  packages/documentation-spa/docs/microservices/feedback/image_0.png
  packages/documentation-spa/docs/microservices/feedback/image_1.png
  packages/documentation-spa/docs/microservices/feedback/image_2.png
  packages/documentation-spa/docs/microservices/feedback/image_3.png
  packages/documentation-spa/docs/microservices/feedback/image_4.png
  packages/documentation-spa/docs/microservices/feedback/image_5.png
  packages/documentation-spa/docs/microservices/feedback/image_6.png
  packages/documentation-spa/docs/microservices/feedback/image_7.png
  packages/documentation-spa/docs/microservices/feedback/image_8.png
  packages/documentation-spa/docs/microservices/feedback/image_9.png
Labels: documentation

#997 fix(ssi): Replaced the deprecated getHomeType query with the new apps query
  packages/ssi-service/.env.example
  packages/ssi-service/src/feedback-panel/api.js
  packages/ssi-service/src/nav/api.js
Labels: bug

#995 feat(apps-service): Additional fields to the app service, and a fix for the appId
  packages/apps-service/src/modules/apps/model.ts
  packages/apps-service/src/modules/apps/resolver.ts
  packages/apps-service/src/modules/apps/schema.gql.ts
Labels: bug

#998 fix(dev-console): Adds new appId and ownerId fields
  packages/developer-console-spa/src/App.css
  packages/developer-console-spa/src/components/AddAppForm.tsx
  packages/developer-console-spa/src/components/AppCard.tsx
  packages/developer-console-spa/src/components/AppOverview.tsx
  packages/developer-console-spa/src/components/Sidebar.tsx
  packages/developer-console-spa/src/hooks/useAppAPI.ts
  packages/developer-console-spa/src/utils/gql-queries/app-by-appid.ts
  packages/developer-console-spa/src/utils/gql-queries/my-apps.ts
  packages/developer-console-spa/src/utils/gql-queries/new-app.ts
Labels: bug

#999 fix(ssi-nav): Incorrect variable name in app drawer in SSI
  packages/ssi-service/src/nav/nav.js
Labels: bug

#1003 fix(#1002) - Remove entityType from home-spa gql and add DEPLOY_URL in env
  packages/home-spa/.env.example
  packages/home-spa/README.md
  packages/home-spa/src/404/404.js
  packages/home-spa/src/res/mocks/stub.js
  packages/home-spa/src/service/service.js
  packages/home-spa/src/tests/404.spec.js
  packages/home-spa/src/tests/home.spec.js
  packages/home-spa/src/tests/index.spec.js
Labels: bug, chore

#1005 Feat#1142&1073: GraphQL query & mutation updates as per the API
  packages/user-group-service/package.json
  packages/user-group-spa/README.md
  packages/user-group-spa/package.json
  packages/user-group-spa/src/components/Form.jsx
  packages/user-group-spa/src/components/Group.jsx
  packages/user-group-spa/src/components/Home.jsx
  packages/user-group-spa/src/components/User.jsx
  packages/user-group-spa/src/services/GqlQueries.js
  packages/user-group-spa/src/services/GroupsAPI.js
Labels: chore

#1007 Fix: #1252: Fix for getUserBy code to return _id field when the user is not present in the cache DB
  packages/user-group-service/src/users/resolver.ts
Labels: bug

#1006 (fix:1243) - Changed the queries & Mutations for dependent microservices
  packages/feedback-service/.env.example
  packages/feedback-service/package.json
  packages/feedback-service/src/helpers.ts
  packages/feedback-service/src/resolver.ts
Labels: dependencies

#1008 docs(readme): fix typos
  README.md
  cli/generator-op-microservice/README.md
Labels: documentation
