Repository 1-Platform/one-platform, pull requests merged in 2021-03, with the labels that each got.

#901 chore(renovate-schedule): Changes renovate schedule to monthly
  renovate.json
Labels: chore

#900 fix(404-page): Adds htaccess for 404 page (in the home-spa)
  packages/home-spa/.htaccess
  packages/home-spa/src/404.html
  packages/home-spa/src/index.html
  packages/home-spa/webpack.config.js
Labels: enhancement

#904 fix(#903) - Changed SSI svgs to outline svgs
  packages/ssi-service/src/default.html
  packages/ssi-service/src/nav/assets.js
  packages/ssi-service/src/nav/nav.css
  packages/ssi-service/src/nav/nav.js
Labels: chore

#905 fix - 978: Included the categorization based on the input entry of feedback and seperated bug field
  packages/feedback-service/src/resolver.ts
  packages/feedback-service/src/schema.ts
  packages/feedback-service/src/typedef.graphql
  packages/feedback-service/src/types.d.ts
Labels: chore

#908 added tests for ssi
  e2e/integration/ssi.js
  package.json
Labels: chore

#909 hotfix(gh-actions): Changes api-gateway image namespace to 1-Platform
  .github/workflows/build-api-gateway.yml
Labels: regression

#911 feat:(1058) - Implemented the design change of Search SPA
  packages/search-spa/package-lock.json
  packages/search-spa/package.json
  packages/search-spa/set-env.ts
  packages/search-spa/src/app/app.component.html
  packages/search-spa/src/app/app.component.ts
  packages/search-spa/src/app/app.module.ts
  packages/search-spa/src/app/search/search.component.html
  packages/search-spa/src/app/search/search.component.scss
  packages/search-spa/src/app/search/search.component.ts
  packages/search-spa/src/assets/icons/dsal.svg
  packages/search-spa/src/assets/icons/feedback.svg
  packages/search-spa/src/assets/icons/mod.svg
  packages/search-spa/src/assets/icons/outages.svg
  packages/search-spa/src/assets/no_search_result.svg
Labels: enhancement

#914 fix(1089): Locked the patternfly version to 4.90.5 nd fixed the open/close property of the modal.
  packages/feedback-spa/public/index.html
  packages/feedback-spa/src/components/ListFeedback.vue
  packages/feedback-spa/src/views/Home.vue
Labels: dependencies

#917 fix(ghcr): Adds static actor for container build gh-actions
  .github/workflows/build-api-gateway.yml
  .github/workflows/build-apps-service.yml
  .github/workflows/build-feedback-service.yml
  .github/workflows/build-notifications-service.yml
  .github/workflows/build-search-service.yml
  .github/workflows/build-user-group-service.yml
Labels: bug

#922 (fix:949) - Fixed the URL and title Parameter formatting issues with script
  packages/search-service/src/search-mapping/cron.ts
  packages/search-service/src/search-mapping/schema.ts
  packages/search-service/src/search-mapping/typedef.graphql
  packages/search-service/src/types.d.ts
Labels: bug

#919 (fix:1089,1090) - Fixed the search results for the feedback SPA
  packages/feedback-spa/src/views/Home.vue
Labels: bug
