Repository 1-Platform/one-platform, pull requests merged in 2022-03, with the labels that each got.

#1474 test(e2e): enabling inline assets feature so that new asset folder is not created for fix for email summary
  cypress.json
  cypress/plugins/index.js
  e2e/summarize.js
  package-lock.json
  package.json
Labels: test-automation

#1476 feat(1882,1912): lighthouse-spa - added lh server url in dashboard and leaderboard pagination
  packages/lighthouse-spa/package-lock.json
  packages/lighthouse-spa/package.json
  packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.html
  packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.ts
  packages/lighthouse-spa/src/app/leaderboard/pages/leaderboard/leaderboard.component.html
Labels: bug, enhancement

#1477 test(e2e): added timeouts for handling auth.stage redirection and added lighthouse leaderboard test(search,sort and checking the record filter)…
  cypress/support/index.js
  e2e/integration/apicatalogtests.js
  e2e/integration/devconsoletests.js
  e2e/integration/feedbacktests.js
  e2e/integration/lighthousetests.js
  e2e/integration/searchtests.js
  e2e/integration/ssitests.js
  e2e/integration/usergrouptests.js
  package-lock.json
  package.json
Labels: test-automation

#1478 chore(lighthouse-spa): removed comment from analytics html
  packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.html
Labels: chore

#1480 fix(1922): app-service - fixed undefined error on appId default function
  packages/apps-service/package-lock.json
  packages/apps-service/package.json
  packages/apps-service/src/modules/apps/model.ts
Labels: bug

#1482 test(e2e): added home spa page static tests
  cypress.json
  e2e/integration/homepagetests.js
  e2e/integration/searchtests.js
Labels: test-automation

#1483 hotfix(apps): Update docker runtime command
  packages/apps-service/Dockerfile
  packages/apps-service/package.json
Labels: enhancement

#1487 1925 - Updated the path of rhel developers guide app
  packages/reverse-proxy-service/src/restricted-spas/index.ts
Labels: enhancement

#1484 test(e2e): added sort test for lighthouse leaderboard total column and removal of unnecessary timeouts from individual command
  cypress.json
  e2e/integration/apicatalogtests.js
  e2e/integration/devconsoletests.js
  e2e/integration/feedbacktests.js
  e2e/integration/homepagetests.js
  e2e/integration/lighthousetests.js
  e2e/integration/searchtests.js
  e2e/integration/ssitests.js
  e2e/integration/usergrouptests.js
  e2e/summarize.js
  package-lock.json
Labels: test-automation

#1488 fix(1868): opc-base fixed link notification
  packages/opc-base/package-lock.json
  packages/opc-base/package.json
  packages/opc-base/src/components/opc-toast/opc-toast.ts
Labels: bug

#1492 fix(1491) - HOT-FIX - .htaccess fix for home-spa
  packages/home-spa/.eleventy.js
Labels: bug

#1495 chore(1494) - Check home-spa and component-catalog-spa update to node 16 and npm 8
  packages/component-catalog-spa/package-lock.json
  packages/home-spa/package-lock.json
Labels: chore, dependencies

#1498 fix(1868): user-group spa fixed link tag in toast
  packages/user-group-spa/package-lock.json
  packages/user-group-spa/package.json
  packages/user-group-spa/public/index.html
Labels: bug

#1497 test(e2e): added common login function to be used, dev console test fix, validations for count of apps in dev console,database and lighthouse screen visibilty test
  e2e/integration/apicatalogtests.js
  e2e/integration/devconsoletests.js
  e2e/integration/feedbacktests.js
  e2e/integration/homepagetests.js
  e2e/integration/lighthousetests.js
  e2e/integration/searchtests.js
  e2e/integration/ssitests.js
  e2e/integration/usergrouptests.js
Labels: test-automation

#1500 chore(1499) - Replace to eleventy-plugin-sass package as it's deprecated
  packages/home-spa/package-lock.json
  packages/home-spa/package.json
Labels: bug, chore

#1504 chore(1581): upgraded lighthouse-spa to node v16
  packages/lighthouse-spa/package-lock.json
Labels: chore

#1506 chore(1978): updated lighthouse-service to node v16
  packages/lighthouse-service/package-lock.json
  packages/lighthouse-service/package.json
  packages/lighthouse-service/src/helpers.ts
Labels: bug, chore

#1502 Chore/1501 - Update SPAs with npm 8 (new package-lock.json)
  .nvmrc
  packages/developer-console-spa/package-lock.json
  packages/documentation-spa/package-lock.json
  packages/feedback-spa/package-lock.json
  packages/search-spa/package-lock.json
  packages/user-group-service/package-lock.json
  packages/user-group-spa/package-lock.json
  packages/user-group-spa/public/mockServiceWorker.js
Labels: chore, dependencies

#1508 fix(1796): api-catalog-spa added padding to pagination in table
  packages/api-catalog-spa/package-lock.json
  packages/api-catalog-spa/package.json
  packages/api-catalog-spa/src/App.scss
  packages/api-catalog-spa/src/pages/APIListPage/APIListPage.tsx
Labels: bug, chore

#1515 chore(search-service): upgrade node to v16
  packages/search-service/Dockerfile
  packages/search-service/package-lock.json
  packages/search-service/package.json
Labels: chore, dependencies

#1514 chore(apps-service): upgrade node to v16
  packages/apps-service/Dockerfile
  packages/apps-service/package-lock.json
  packages/apps-service/package.json
Labels: chore, dependencies

#1513 chore(api-gateway): upgrade node to v16
  packages/api-gateway-service/Dockerfile
  packages/api-gateway-service/package-lock.json
  packages/api-gateway-service/package.json
Labels: chore

#1510 chore(feedback-service): updated to node v16
  packages/feedback-service/Dockerfile
  packages/feedback-service/package-lock.json
Labels: chore

#1509 chore(1980): updated api-catalog service to node v16
  packages/api-catalog-service/Dockerfile
  packages/api-catalog-service/package-lock.json
  packages/api-catalog-service/package.json
  packages/api-catalog-service/src/shared/helpers.ts
Labels: chore

#1512 test(e2e):added test for checking bug and feedback image getting loaded in feedback spa
  e2e/integration/feedbacktests.js
Labels: test-automation

#1516 chore: api-catalog-spa linux compatible lock file
  packages/api-catalog-spa/package-lock.json
Labels: chore

#1517 fix(api-catalog-spa): homepage url makes screen blank
  packages/api-catalog-spa/package-lock.json
  packages/api-catalog-spa/package.json
  packages/api-catalog-spa/src/App.tsx
  packages/api-catalog-spa/src/router/Router.tsx
Labels: bug

#1519 chore(notifications-service): upgrade node to v16
  packages/notifications-service/Dockerfile
  packages/notifications-service/package-lock.json
  packages/notifications-service/package.json
  packages/notifications-service/service.ts
  packages/notifications-service/src/notificationTemplates/schema.ts
  packages/notifications-service/src/schema.ts
  packages/notifications-service/src/types.d.ts
Labels: bug, chore, dependencies

#1518 test(e2e):Lighthouse projects page,user group and feedback spa record count test and api catalog explore tab filter test…
  e2e/integration/apicatalogtests.js
  e2e/integration/feedbacktests.js
  e2e/integration/lighthousetests.js
  e2e/integration/usergrouptests.js
Labels: test-automation

#1520 fix(api-catalog-spa): fixed failing test in api catalog spa
  packages/api-catalog-spa/package.json
  packages/api-catalog-spa/src/App.test.tsx
Labels: bug

#1521 feat(rproxy): redirect for rhel-developer-guide
  packages/reverse-proxy-service/src/restricted-spas/index.ts
Labels: enhancement

#1503 chore(1496) - Automated test and build on github for all microservices and SPA
  .github/workflows/test-and-build.yml
  .gitignore
  README.md
  package.json
  packages/api-catalog-service/.gitignore
  packages/api-catalog-service/.test.env
  packages/api-catalog-service/package.json
  packages/api-catalog-spa/.test.env
  packages/api-gateway-service/.gitignore
  packages/api-gateway-service/.test.env
  packages/api-gateway-service/package.json
  packages/apps-service/.test.env
  packages/apps-service/package.json
  packages/component-catalog-spa/.test.env
  packages/component-catalog-spa/package.json
  packages/developer-console-spa/.test.env
  packages/developer-console-spa/package.json
  packages/documentation-spa/.test.env
  packages/feedback-service/.gitignore
  packages/feedback-service/.test.env
  packages/feedback-service/package.json
  packages/feedback-spa/.test.env
  packages/feedback-spa/package.json
  packages/home-spa/.gitignore
  packages/home-spa/.test.env
  packages/home-spa/package.json
  packages/lighthouse-service/.gitignore
  packages/lighthouse-service/.test.env
  packages/lighthouse-service/package.json
  packages/lighthouse-spa/.test.env
  packages/lighthouse-spa/package.json
  packages/notifications-service/.gitignore
  packages/notifications-service/.test.env
  packages/notifications-service/package.json
  packages/reverse-proxy-service/package.json
  packages/search-service/.gitignore
  packages/search-service/.test.env
  packages/search-service/package.json
  packages/search-spa/.test.env
  packages/search-spa/package.json
  packages/user-group-service/.gitignore
  packages/user-group-service/.test.env
  packages/user-group-service/package.json
  packages/user-group-spa/.test.env
  packages/user-group-spa/package.json
Labels: enhancement, chore, dependencies, test-automation
