Repository 1-Platform/one-platform, pull requests merged in 2022-04, with the labels that each got.

#1527 fix(1985): lighthouse-spa fixed case sensitive project search and improved leaderboard precision
  packages/lighthouse-spa/package-lock.json
  packages/lighthouse-spa/package.json
  packages/lighthouse-spa/src/app/shared/components/table/table.component.html
  packages/lighthouse-spa/src/app/shared/components/table/table.component.scss
  packages/lighthouse-spa/src/app/shared/components/table/table.component.spec.ts
  packages/lighthouse-spa/src/app/shared/components/table/table.component.ts
  packages/lighthouse-spa/src/app/shared/pipes/filter-list.pipe.spec.ts
  packages/lighthouse-spa/src/app/shared/pipes/filter-list.pipe.ts
  packages/lighthouse-spa/src/app/shared/pipes/floor.pipe.spec.ts
  packages/lighthouse-spa/src/app/shared/pipes/floor.pipe.ts
  packages/lighthouse-spa/src/app/shared/pipes/get-decimal.pipe.spec.ts
  packages/lighthouse-spa/src/app/shared/pipes/get-decimal.pipe.ts
  packages/lighthouse-spa/src/app/shared/shared.module.ts
  packages/lighthouse-spa/src/app/utils/leaderboardTable.ts
Labels: bug

#1526 feat(1988): lighthouse-service changed leaderboard to float for better precision
  packages/lighthouse-service/package-lock.json
  packages/lighthouse-service/package.json
  packages/lighthouse-service/src/lighthouse-db-manager/lighthouse-db-manager.ts
  packages/lighthouse-service/src/lighthouse-spa-config/helpers.ts
  packages/lighthouse-service/src/lighthouse-spa-config/resolver.ts
  packages/lighthouse-service/src/lighthouse-spa-config/typedef.graphql
Labels: enhancement

#1523 test(e2e): added test scripts for checking footer links and search in sidebar
  e2e/integration/homepagetests.js
  e2e/integration/ssitests.js
  e2e/pageObject/Footer.js
  e2e/pageObject/HomePage.js
  e2e/pageObject/Sidebar.js
Labels: test-automation

#1525 fix(1524) - Update the One Platform Source Link to point to correct url on Source
  packages/component-catalog-spa/package-lock.json
  packages/component-catalog-spa/package.json
  packages/component-catalog-spa/src/Components/Navbar.jsx
  packages/component-catalog-spa/src/Configs/footer.js
Labels: bug, chore

#1529 test(e2e): lighthouse config page test scenarios(create project,delete project)
  e2e/integration/devconsoletests.js
Labels: test-automation

#1528 fix(dev-console): changed lighthouse config page using app.id to appId
  packages/developer-console-spa/package-lock.json
  packages/developer-console-spa/package.json
  packages/developer-console-spa/src/components/ConfigureLighthouse.tsx
  packages/developer-console-spa/src/components/lighthouse/LinkProjectForm.tsx
Labels: bug

#1532 feat(search-service): search map schema changes
  docker-compose.yml
  packages/search-service/package-lock.json
  packages/search-service/package.json
  packages/search-service/service.ts
  packages/search-service/src/search-mapping/resolver.ts
  packages/search-service/src/search-mapping/typedef.graphql
  packages/search-service/src/search-mapping/types.d.ts
Labels: enhancement

#1533 tests(app-service): added tests for apps module
  packages/apps-service/.eslintignore
  packages/apps-service/.eslintrc.js
  packages/apps-service/.prettierrc
  packages/apps-service/.test.env
  packages/apps-service/jest.config.js
  packages/apps-service/package-lock.json
  packages/apps-service/package.json
  packages/apps-service/src/__tests__/apps.spec.ts
  packages/apps-service/src/__tests__/mocks/mockDatabase.ts
  packages/apps-service/src/__tests__/query.gql.ts
  packages/apps-service/src/app.ts
  packages/apps-service/src/index.ts
  packages/apps-service/src/setup/database.ts
  packages/apps-service/src/setup/env.ts
  packages/apps-service/tsconfig.json
  packages/apps-service/tsconfig.prod.json
Labels: chore, tests

#1531 feat(dev-console): Implement search config form
  packages/developer-console-spa/package-lock.json
  packages/developer-console-spa/package.json
  packages/developer-console-spa/src/@types/Search/types.d.ts
  packages/developer-console-spa/src/App.tsx
  packages/developer-console-spa/src/components/ConfigureSearch/SearchWizardForm.tsx
  packages/developer-console-spa/src/components/ConfigureSearch/Steps/Step1.tsx
  packages/developer-console-spa/src/components/ConfigureSearch/Steps/Step2.tsx
  packages/developer-console-spa/src/components/ConfigureSearch/Steps/Step3.tsx
  packages/developer-console-spa/src/components/ConfigureSearch/Steps/store.ts
  packages/developer-console-spa/src/components/ConfigureSearch/Steps/types.d.ts
  packages/developer-console-spa/src/components/ConfigureSearch/global.d.ts
  packages/developer-console-spa/src/components/ConfigureSearch/index.tsx
  packages/developer-console-spa/src/components/NotFound.tsx
  packages/developer-console-spa/src/hooks/useSearchConfig.ts
  packages/developer-console-spa/src/services/searchConfig.ts
  packages/developer-console-spa/src/utils/gql-queries/app-search-config.ts
  packages/developer-console-spa/src/utils/gql-queries/index.ts
  packages/developer-console-spa/src/utils/gql-queries/update-search-config.ts
Labels: enhancement

#1535 chore(rproxy): remove redundant route resolvers
  packages/reverse-proxy-service/src/restricted-spas/index.ts
  packages/reverse-proxy-service/src/spec/restricted-spas.spec.ts
Labels: chore

#1534 test(e2e): User group SPA additional test cases(invalid search,notification message, breadcrumb,documentation link redirection)
  cypress.json
  cypress/support/index.js
  e2e/integration/usergrouptests.js
  package-lock.json
  package.json
Labels: test-automation

#1537 test(e2e): check for not found image,send feedback link and time taken for search visibility test
  e2e/integration/searchtests.js
Labels: test-automation

#1539 test(e2e): Developer Console Search and Op-Navbar tests
  e2e/helper/apps.list.js
  e2e/integration/devconsoletests.js
Labels: test-automation
