Repository 1-Platform/one-platform, pull requests merged in 2022-02, with the labels that each got.

#1444 test(feedbackanddevconsole):added new test cases for new feedback spa and modified devconsole failing tests for feedback module
  cypress.json
  e2e/integration/devconsoletests.js
  e2e/integration/feedbacktests.js
Labels: test-automation

#1447 hotfix(feedback-service): fixed status filter not working
  packages/feedback-service/package-lock.json
  packages/feedback-service/package.json
  packages/feedback-service/src/feedbacks/resolver.ts
Labels: bug

#1445 feat(1835): Lighthouse SPA - implemented new leaderboard
  packages/lighthouse-spa/package-lock.json
  packages/lighthouse-spa/package.json
  packages/lighthouse-spa/src/app/dashboard/dashboard.gql.ts
  packages/lighthouse-spa/src/app/dashboard/dashboard.module.ts
  packages/lighthouse-spa/src/app/dashboard/dashboard.service.spec.ts
  packages/lighthouse-spa/src/app/dashboard/dashboard.service.ts
  packages/lighthouse-spa/src/app/dashboard/mock-dashboard.ts
  packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.html
  packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.spec.ts
  packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.ts
  packages/lighthouse-spa/src/app/leaderboard/enum.ts
  packages/lighthouse-spa/src/app/leaderboard/leaderboard.gql.ts
  packages/lighthouse-spa/src/app/leaderboard/leaderboard.module.ts
  packages/lighthouse-spa/src/app/leaderboard/leaderboard.service.spec.ts
  packages/lighthouse-spa/src/app/leaderboard/leaderboard.service.ts
  packages/lighthouse-spa/src/app/leaderboard/mock-leaderboard.ts
  packages/lighthouse-spa/src/app/leaderboard/pages/leaderboard/leaderboard.component.html
  packages/lighthouse-spa/src/app/leaderboard/pages/leaderboard/leaderboard.component.scss
  packages/lighthouse-spa/src/app/leaderboard/pages/leaderboard/leaderboard.component.spec.ts
  packages/lighthouse-spa/src/app/leaderboard/pages/leaderboard/leaderboard.component.ts
  packages/lighthouse-spa/src/app/leaderboard/types.d.ts
  packages/lighthouse-spa/src/app/shared/components/table/table.component.html
  packages/lighthouse-spa/src/app/shared/components/table/table.component.scss
  packages/lighthouse-spa/src/app/shared/components/table/table.component.spec.ts
  packages/lighthouse-spa/src/app/shared/components/table/table.component.ts
  packages/lighthouse-spa/src/app/shared/shared.module.ts
  packages/lighthouse-spa/src/app/utils/leaderboardTable.ts
  packages/lighthouse-spa/src/styles.scss
Labels: enhancement

#1453 hotfix(lighthouse-spa): removed asc sort order in dashboard leaderboard and made line chart responsive
  packages/lighthouse-spa/package-lock.json
  packages/lighthouse-spa/package.json
  packages/lighthouse-spa/src/app/dashboard/dashboard.gql.ts
  packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.html
  packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.scss
  packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.ts
  packages/lighthouse-spa/src/app/utils/leaderboardTable.ts
Labels: enhancement

#1449 feat(dev-console): added feedback spa link in feedback list page
  packages/developer-console-spa/package-lock.json
  packages/developer-console-spa/package.json
  packages/developer-console-spa/src/components/feedback/FeedbackList.tsx
Labels: bug, enhancement

#1459 fix(user-spa): Fix for groups in user profile
  packages/user-group-spa/package-lock.json
  packages/user-group-spa/src/components/User.jsx
Labels: bug

#1455 test(e2e): changes done in search,ssi,usergroup spa to support new features (ui changes)
  cypress.json
  e2e/integration/devconsoletests.js
  e2e/integration/feedbacktests.js
  e2e/integration/lighthousetests.js
  e2e/integration/searchtests.js
  e2e/integration/ssitests.js
  e2e/integration/usergrouptests.js
Labels: test-automation

#1461 test(apicatalog):added timeouts to wait for an element
  e2e/integration/apicatalogtests.js
Labels: test-automation

#1443 chore(dev-console): Refactor and code cleanup
  packages/developer-console-spa/package-lock.json
  packages/developer-console-spa/package.json
  packages/developer-console-spa/public/chrome.html
  packages/developer-console-spa/src/App.tsx
  packages/developer-console-spa/src/components/AddAppForm.tsx
  packages/developer-console-spa/src/components/AppCard.tsx
  packages/developer-console-spa/src/components/AppOverview.tsx
  packages/developer-console-spa/src/components/ConfigureCouchDB.tsx
  packages/developer-console-spa/src/components/ConfigureDatabase.tsx
  packages/developer-console-spa/src/components/ConfigureOPCBase.module.css
  packages/developer-console-spa/src/components/ConfigureOPNavbar.test.tsx
  packages/developer-console-spa/src/components/ConfigureOPNavbar.tsx
  packages/developer-console-spa/src/components/Sidebar.css
  packages/developer-console-spa/src/components/Sidebar.tsx
  packages/developer-console-spa/src/components/database/AddUserForm.tsx
  packages/developer-console-spa/src/components/database/CreateDBForm.tsx
  packages/developer-console-spa/src/components/database/DeleteDBForm.tsx
  packages/developer-console-spa/src/components/database/UpdateDBConfig.tsx
  packages/developer-console-spa/src/components/database/UsersTable.tsx
  packages/developer-console-spa/src/index.tsx
Labels: bug, enhancement, chore

#1462 hotfix(dev-console): fix var reassignment
  packages/developer-console-spa/src/components/ConfigureDatabase.tsx
Labels: bug

#1467 feat(1865): api-catalog-spa - changed no-cors url format and fixed type error
  packages/api-catalog-spa/package-lock.json
  packages/api-catalog-spa/package.json
  packages/api-catalog-spa/src/pages/ApiCUDPage/ApiCUDPage.tsx
  packages/api-catalog-spa/src/pages/ApiCUDPage/hooks/useGetANamespace.tsx
  packages/api-catalog-spa/src/pages/ApiDescriptionPage/ApiDescriptionPage.tsx
  packages/api-catalog-spa/src/pages/ApiDescriptionPage/hooks/useGetANamespace.tsx
  packages/api-catalog-spa/src/pages/GqlPlaygroundPage/GqlPlaygroundPage.tsx
  packages/api-catalog-spa/src/pages/GqlPlaygroundPage/hooks/useGetANamespace.tsx
  packages/api-catalog-spa/src/pages/SwaggerToolPage/SwaggerToolPage.tsx
  packages/api-catalog-spa/src/pages/SwaggerToolPage/hooks/useGetANamespace.tsx
  packages/api-catalog-spa/src/pages/VoyagerToolPage/VoyagerToolPage.tsx
  packages/api-catalog-spa/src/pages/VoyagerToolPage/hooks/useGetANamespace.tsx
Labels: bug, enhancement

#1466 feat(1865): reverse-proxy - fixed params missing in no-cors redirect
  packages/reverse-proxy-service/package-lock.json
  packages/reverse-proxy-service/package.json
  packages/reverse-proxy-service/src/no-cors-proxy/index.ts
  packages/reverse-proxy-service/src/no-cors-proxy/resolver.ts
Labels: bug

#1469 fix(reverse-proxy): fixed no-cors-proxy url issue
  packages/reverse-proxy-service/package-lock.json
  packages/reverse-proxy-service/package.json
  packages/reverse-proxy-service/src/couchdb/index.ts
  packages/reverse-proxy-service/src/no-cors-proxy/index.ts
  packages/reverse-proxy-service/src/no-cors-proxy/resolver.ts
Labels: bug

#1464 feat(1873): lighthouse-service: leaderboard updated to branch based and improved accuracy
  packages/lighthouse-service/package-lock.json
  packages/lighthouse-service/package.json
  packages/lighthouse-service/src/audit-manager/resolver.ts
  packages/lighthouse-service/src/audit-manager/typedef.graphql
  packages/lighthouse-service/src/e2e/lighthouse.spec.ts
  packages/lighthouse-service/src/lighthouse-db-manager/lighthouse-db-manager.ts
  packages/lighthouse-service/src/lighthouse-db-manager/types.ts
Labels: enhancement

#1465 feat(1873): lighthouse-spa : updated leaderboards with query change
  packages/lighthouse-spa/package-lock.json
  packages/lighthouse-spa/package.json
  packages/lighthouse-spa/src/app/dashboard/dashboard.gql.ts
  packages/lighthouse-spa/src/app/dashboard/dashboard.service.spec.ts
  packages/lighthouse-spa/src/app/dashboard/dashboard.service.ts
  packages/lighthouse-spa/src/app/dashboard/mock-dashboard.ts
  packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.html
  packages/lighthouse-spa/src/app/dashboard/pages/analysis/analysis.component.ts
  packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.spec.ts
  packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.ts
  packages/lighthouse-spa/src/app/leaderboard/leaderboard.gql.ts
  packages/lighthouse-spa/src/app/leaderboard/mock-leaderboard.ts
  packages/lighthouse-spa/src/app/leaderboard/types.d.ts
  packages/lighthouse-spa/src/app/utils/leaderboardTable.ts
Labels: bug, enhancement

#1468 hotfix(dev-console): Add scope to sidebar css rules
  packages/developer-console-spa/src/components/Sidebar.css
Labels: bug

#1460 chore(1872): updated all sentry release name and updated sentry to latest version
  packages/api-catalog-spa/package-lock.json
  packages/api-catalog-spa/package.json
  packages/api-catalog-spa/src/index.tsx
  packages/component-catalog-spa/package-lock.json
  packages/component-catalog-spa/package.json
  packages/component-catalog-spa/src/index.jsx
  packages/developer-console-spa/package-lock.json
  packages/developer-console-spa/package.json
  packages/developer-console-spa/src/index.tsx
  packages/documentation-spa/package-lock.json
  packages/documentation-spa/package.json
  packages/documentation-spa/src/theme/Layout/index.jsx
  packages/feedback-spa/package-lock.json
  packages/feedback-spa/package.json
  packages/feedback-spa/src/main.tsx
  packages/home-spa/package-lock.json
  packages/home-spa/package.json
  packages/home-spa/src/_includes/partials/header.njk
  packages/lighthouse-spa/package-lock.json
  packages/lighthouse-spa/package.json
  packages/lighthouse-spa/src/main.ts
  packages/search-spa/package-lock.json
  packages/search-spa/package.json
  packages/search-spa/src/main.ts
  packages/user-group-spa/package-lock.json
  packages/user-group-spa/package.json
  packages/user-group-spa/src/index.js
Labels: chore

#1470 test(e2e): enabling the json report for the email summary
  cypress.json
Labels: test-automation

#1472 fix(dev-console): prepend appId to sidebar links
  packages/developer-console-spa/src/components/Sidebar.tsx
Labels: bug

#1471 test(e2e):fix devconsole locators and changed report file name for email summary
  e2e/integration/devconsoletests.js
  e2e/summarize.js
Labels: test-automation

#1473 test(e2e):removed redundant test code as it is being handled in index.js
  cypress/support/index.js
  e2e/integration/apicatalogtests.js
  e2e/integration/devconsoletests.js
  e2e/integration/feedbacktests.js
  e2e/integration/lighthousetests.js
  e2e/integration/searchtests.js
  e2e/integration/ssitests.js
  e2e/integration/usergrouptests.js
  e2e/summarize.js
Labels: test-automation
