Repository 1-Platform/one-platform, pull requests merged in 2022-12, with the labels that each got.

#1673 fix(dev-console): project service fix
  packages/developer-console-spa/package-lock.json
  packages/developer-console-spa/package.json
  packages/developer-console-spa/src/common/services/project.ts
  packages/developer-console-spa/src/pages/ProjectSettings/General.tsx
  packages/developer-console-spa/src/pages/ProjectSettings/index.tsx
Labels: bug

#1672 chore(ci-lighthouse) - Add lighthouse support in CI
  .github/workflows/auto-deployments.yml
  .github/workflows/manual-deployment.yml
  packages/home-spa/.env.example
Labels: enhancement, chore

#1675 Enforcing npm version for renovate
  package-lock.json
  package.json
Labels: chore

#1671 fix(apps): added sparse + unique keys for hosting
  packages/apps-service/src/modules/projects/model.ts
Labels: bug

#1679 fix(lighthouse-ci) - Removed from auto-deployments pipeline
  .github/workflows/auto-deployments.yml
  .github/workflows/manual-deployment.yml
Labels: dependencies

#1681 fix(lighthouse-only-keep-prod-ci) - Removed from auto-deployments pipeline
  .github/workflows/auto-deployments.yml
  .github/workflows/manual-deployment.yml
Labels: enhancement

#1682 feat(apps): Optimized apps service image using multi-stage builds
  packages/apps-service/Dockerfile
  packages/apps-service/package-lock.json
  packages/apps-service/package.json
  packages/apps-service/src/modules/projects/schema.gql.ts
Labels: bug, chore

#1683 fix(apps): fix for multi file copy in dockerfile
  packages/apps-service/Dockerfile
Labels: bug
