Repository 1-Platform/one-platform, pull requests merged in 2022-06, with the labels that each got.

#1565 Chore(home-spa-test) - Changed home-spa stats
  packages/home-spa/package-lock.json
  packages/home-spa/package.json
  packages/home-spa/src/_data/footer.json
  packages/home-spa/src/_data/pageText.json
Labels: chore

#1564 1417 - Updated the search to the New UI
  packages/search-spa/package-lock.json
  packages/search-spa/package.json
  packages/search-spa/src/app/search/search.component.html
  packages/search-spa/src/app/search/search.component.scss
  packages/search-spa/src/app/search/search.component.ts
  packages/search-spa/src/app/utils/pagination.ts
  packages/search-spa/src/assets/app-cube.svg
  packages/search-spa/src/index.html
Labels: enhancement

#1566 feat(2086): lh-spa - added lh doc url on getting started
  packages/lighthouse-spa/set-env.ts
  packages/lighthouse-spa/src/app/shared/layouts/app-layout/app-layout.component.html
  packages/lighthouse-spa/src/app/shared/layouts/app-layout/app-layout.component.ts
  packages/lighthouse-spa/src/environments/environment.prod.ts
  packages/lighthouse-spa/src/environments/environment.ts
Labels: enhancement

#1570 feat(2114,2076): api-catalog-spa implemented cmdb and outage integration
  packages/api-catalog-spa/package-lock.json
  packages/api-catalog-spa/package.json
  packages/api-catalog-spa/src/api/types.ts
  packages/api-catalog-spa/src/pages/APICUDPage/APICUDPage.helpers.ts
  packages/api-catalog-spa/src/pages/APICUDPage/APICUDPage.tsx
  packages/api-catalog-spa/src/pages/APICUDPage/APICUDPage.types.ts
  packages/api-catalog-spa/src/pages/APICUDPage/components/APIBasicDetailsForm/APIBasicDetailsForm.tsx
  packages/api-catalog-spa/src/pages/APICUDPage/components/APIReview/APIReview.tsx
  packages/api-catalog-spa/src/pages/APICUDPage/components/APISchemaForm/APISchemaForm.tsx
  packages/api-catalog-spa/src/pages/APICUDPage/hooks/index.tsx
  packages/api-catalog-spa/src/pages/APICUDPage/hooks/useGetANamespaceBySlug.tsx
  packages/api-catalog-spa/src/pages/APICUDPage/hooks/useGetOutages.tsx
  packages/api-catalog-spa/src/pages/APIDescriptionPage/APIDescriptionPage.tsx
  packages/api-catalog-spa/src/pages/APIDescriptionPage/apiDescriptionPage.module.scss
  packages/api-catalog-spa/src/pages/APIDescriptionPage/components/ApiEnvironmentSection/ApiEnvironmentSection.tsx
  packages/api-catalog-spa/src/pages/APIDescriptionPage/components/DetailsSection/DetailsSection.tsx
  packages/api-catalog-spa/src/pages/APIDescriptionPage/hooks/useGetANamespaceBySlug.ts
  packages/api-catalog-spa/src/pages/APIDescriptionPage/hooks/useSubscribeSchema.tsx
  packages/api-catalog-spa/src/pages/HomePage/homePage.module.scss
  packages/api-catalog-spa/src/utils/hasUserApiEditAccess.ts
Labels: bug, enhancement

#1569 feat(2114,2076): api-catalog-backend implemented cmdb code support and status outage
  packages/api-catalog-service/.env.example
  packages/api-catalog-service/package-lock.json
  packages/api-catalog-service/package.json
  packages/api-catalog-service/src/@types/graph.d.ts
  packages/api-catalog-service/src/app.ts
  packages/api-catalog-service/src/config.ts
  packages/api-catalog-service/src/dataloaders/index.ts
  packages/api-catalog-service/src/dataloaders/outageStatusLoader.ts
  packages/api-catalog-service/src/dataloaders/userLoader.ts
  packages/api-catalog-service/src/datasources/cmdbDatasourceAPI.ts
  packages/api-catalog-service/src/datasources/outageStatusAPI.ts
  packages/api-catalog-service/src/datasources/types.ts
  packages/api-catalog-service/src/db/namespace.ts
  packages/api-catalog-service/src/db/specSheet.ts
  packages/api-catalog-service/src/db/types.ts
  packages/api-catalog-service/src/graph/namespace/resolver.ts
  packages/api-catalog-service/src/graph/namespace/typedef.graphql
  packages/api-catalog-service/src/graph/types.ts
  packages/api-catalog-service/src/subscriptions/setupCronTask.ts
  packages/api-catalog-service/src/subscriptions/subscriptionDAL.ts
  packages/api-catalog-service/src/subscriptions/types.ts
Labels: bug, enhancement
