Repository 1-Platform/one-platform, pull requests merged in 2022-09, with the labels that each got.

#1603 chore(1602) - Add xvfb in CI (test-and-build) to run axe test cases
  .github/workflows/test-and-build.yml
Labels: chore, dependencies

#1608 chore(2251): updated edit doc and blog url in doc-spa
  packages/doc-spa/docusaurus.config.js
  packages/doc-spa/package-lock.json
  packages/doc-spa/package.json
  packages/doc-spa/src/theme/Layout/index.jsx
Labels: bug

#1604 chore(1602-fix) - Setting size as 4096
  .github/workflows/test-and-build.yml
  lerna.json
  nx.json
  package-lock.json
  package.json
  packages/analytics-service/package-lock.json
  packages/api-catalog-service/package-lock.json
  packages/apps-service/package-lock.json
  packages/component-catalog-spa/package.json
  packages/developer-console-spa/package-lock.json
  packages/doc-spa/package-lock.json
  packages/lighthouse-spa/package-lock.json
  packages/notifications-service/package-lock.json
  packages/reverse-proxy-service/package-lock.json
  packages/search-spa/package-lock.json
  packages/search-spa/package.json
  packages/user-group-service/package-lock.json
Labels: chore

#1627 fix(2219): feedback-spa: fixed modal warning
  packages/feedback-spa/package-lock.json
  packages/feedback-spa/package.json
  packages/feedback-spa/src/pages/HomePage/HomePage.tsx
Labels: bug

#1626 docs:2253 - Updated the docs for the the Search and Feedback
  package-lock.json
  package.json
  packages/doc-spa/docs/services/feedback/api-reference.md
  packages/doc-spa/docs/services/feedback/onboarding-guide.md
  packages/doc-spa/docs/services/feedback/overview.md
  packages/doc-spa/docs/services/search/api-reference.md
  packages/doc-spa/package-lock.json
  packages/doc-spa/package.json
Labels: documentation
