Repository 1-Platform/one-platform, pull requests merged in 2022-11, with the labels that each got.

#1642 chore(1639) - Create github pipeline for SPA deployments with SPAship
  .github/workflows/auto-deployments.yml
  .github/workflows/manual-deployment.yml
  packages/home-spa/.env.example
Labels: enhancement

#1647 chore(gh-actions) - Split steps into individual phases(steps)
  .github/workflows/auto-deployments.yml
  .github/workflows/manual-deployment.yml
  packages/home-spa/package-lock.json
Labels: chore

#1649 rproxy: reduce the rate limit of incoming requests
  packages/reverse-proxy-service/src/server.ts
Labels: bug

#1650 fix(gh-actions) - Fixed env for spaship command
  .github/workflows/auto-deployments.yml
  .github/workflows/manual-deployment.yml
  packages/home-spa/.env.example
Labels: bug, tests

#1651 fix(gh-actions-spaship) - Testing deploy action
  .github/workflows/auto-deployments.yml
  .github/workflows/manual-deployment.yml
  packages/home-spa/.env.example
Labels: bug

#1652 fix(multiple-deployments) - Individual builds and test optimisation
  .github/workflows/auto-deployments.yml
  .github/workflows/test-and-build.yml
Labels: enhancement

#1655 fix(api-catalog-spa): fixed renovate downgraded v1
  packages/api-catalog-spa/package-lock.json
Labels: bug

#1657 fix(2361): fixed direct url access failing
  packages/api-catalog-spa/package-lock.json
  packages/api-catalog-spa/package.json
  packages/api-catalog-spa/src/main.tsx
Labels: bug

#1662 chore: fixing accessibility issues
  packages/lighthouse-spa/package-lock.json
  packages/lighthouse-spa/package.json
  packages/lighthouse-spa/src/styles.scss
Labels: chore

#1668 fix(2010,2011): developer console v2 lighthouse modal issues fixed
  packages/developer-console-spa/package-lock.json
  packages/developer-console-spa/package.json
  packages/developer-console-spa/src/common/components/NewProjectForm/index.tsx
  packages/developer-console-spa/src/pages/Home/index.tsx
  packages/developer-console-spa/src/pages/Lighthouse/CreateProjectForm.tsx
  packages/developer-console-spa/src/pages/Lighthouse/LinkProjectForm.tsx
  packages/developer-console-spa/src/pages/Lighthouse/index.tsx
Labels: bug
