Repository 1-Platform/one-platform, pull requests merged in 2022-05, with the labels that each got.

#1543 home-spa - chore(1542) - Home SPA - update Contact us, Source page and Blog links
  packages/home-spa/package-lock.json
  packages/home-spa/package.json
  packages/home-spa/src/_data/footer.json
  packages/home-spa/src/_includes/partials/service.njk
  packages/home-spa/src/contact-us.njk
Labels: chore

#1545 Test(e2e): additional test case scenarios for home spa(verify app link redirections, learn more link redirection)
  cypress.json
  e2e/integration/homepagetests.js
  e2e/pageObject/HomePage.js
Labels: test-automation

#1548 feat(api-gateway): fwd extra fields to services
  docker-compose.yml
  packages/api-gateway-service/package-lock.json
  packages/api-gateway-service/service.ts
  packages/api-gateway-service/src/remote-schema.ts
Labels: enhancement

#1547 feat(rproxy): customizable SSO auth shield
  packages/reverse-proxy-service/.env.example
  packages/reverse-proxy-service/.prettierrc
  packages/reverse-proxy-service/package-lock.json
  packages/reverse-proxy-service/package.json
  packages/reverse-proxy-service/src/app.ts
  packages/reverse-proxy-service/src/couchdb/index.ts
  packages/reverse-proxy-service/src/couchdb/resolver.ts
  packages/reverse-proxy-service/src/index.ts
  packages/reverse-proxy-service/src/middleware/checkSSO.ts
  packages/reverse-proxy-service/src/middleware/jwtAuth.ts
  packages/reverse-proxy-service/src/middleware/oidcAuth.ts
  packages/reverse-proxy-service/src/no-cors-proxy/index.ts
  packages/reverse-proxy-service/src/restricted-spas/index.ts
  packages/reverse-proxy-service/src/restricted-spas/resolver.ts
  packages/reverse-proxy-service/src/server.ts
  packages/reverse-proxy-service/src/setup/database.ts
  packages/reverse-proxy-service/src/setup/env.ts
  packages/reverse-proxy-service/src/setup/logger.ts
  packages/reverse-proxy-service/src/setup/store.ts
  packages/reverse-proxy-service/src/spec/app.spec.ts
  packages/reverse-proxy-service/src/spec/couchdb.spec.ts
  packages/reverse-proxy-service/src/spec/jwtAuth.spec.ts
  packages/reverse-proxy-service/src/spec/restricted-spas.spec.ts
  packages/reverse-proxy-service/src/utils/applicationCache.ts
  packages/reverse-proxy-service/src/utils/logger.ts
  packages/reverse-proxy-service/src/utils/setupJest.ts
  packages/reverse-proxy-service/src/utils/store.ts
  packages/reverse-proxy-service/src/utils/verifyJwtToken.ts
Labels: enhancement

#1549 hot-fix(home-spa) - Hot-fix for home-spa 404 page
  packages/home-spa/src/404.njk
Labels: bug, chore

#1550 test(e2e): added the automation tests for error page
  e2e/integration/errorpagetests.js
Labels: test-automation

#1553 fix(2102): lh-spa - changed homepage cards title to lowercase
  packages/lighthouse-spa/package-lock.json
  packages/lighthouse-spa/package.json
  packages/lighthouse-spa/src/app/dashboard/pages/home/home.component.html
Labels: bug, enhancement

#1536 feat(1982): implemented analytics service with sentry
  docker-compose.yml
  packages/analytics-service/.dockerignore
  packages/analytics-service/.env.example
  packages/analytics-service/.eslintrc.js
  packages/analytics-service/.gitignore
  packages/analytics-service/.prettierrc
  packages/analytics-service/.test.env
  packages/analytics-service/Dockerfile
  packages/analytics-service/README.md
  packages/analytics-service/esbuild.config.js
  packages/analytics-service/jest.config.js
  packages/analytics-service/package-lock.json
  packages/analytics-service/package.json
  packages/analytics-service/src/@types/graph.d.ts
  packages/analytics-service/src/@types/types.d.ts
  packages/analytics-service/src/@types/user.d.ts
  packages/analytics-service/src/__tests__/app.spec.ts
  packages/analytics-service/src/__tests__/mocks/data.ts
  packages/analytics-service/src/__tests__/mocks/mockDatabase.ts
  packages/analytics-service/src/__tests__/query.gql.ts
  packages/analytics-service/src/app.ts
  packages/analytics-service/src/config.ts
  packages/analytics-service/src/dataloader/userLoader.ts
  packages/analytics-service/src/datasource/analyticConfigDB.ts
  packages/analytics-service/src/datasource/sentryAPI.ts
  packages/analytics-service/src/datasource/types.ts
  packages/analytics-service/src/db/analytics.ts
  packages/analytics-service/src/db/types.ts
  packages/analytics-service/src/graph/analyticsConfig/resolver.ts
  packages/analytics-service/src/graph/analyticsConfig/typedef.graphql
  packages/analytics-service/src/graph/analyticsConfig/types.ts
  packages/analytics-service/src/graph/crashlytics/resolver.ts
  packages/analytics-service/src/graph/crashlytics/typedef.graphql
  packages/analytics-service/src/graph/crashlytics/types.ts
  packages/analytics-service/src/graph/types.ts
  packages/analytics-service/src/helpers/buildUserQuery.ts
  packages/analytics-service/src/helpers/index.ts
  packages/analytics-service/src/index.ts
  packages/analytics-service/src/logger.ts
  packages/analytics-service/tsconfig.json
Labels: enhancement

#1554 fix(api-catalog): added default host parameter to server
  packages/api-catalog-service/package-lock.json
  packages/api-catalog-service/package.json
  packages/api-catalog-service/src/app.ts
  packages/api-catalog-service/src/index.ts
Labels: bug

#1556 fix(api-catalog-spa): fixed redoc module vitejs incompatibility
  packages/api-catalog-spa/package-lock.json
  packages/api-catalog-spa/package.json
  packages/api-catalog-spa/src/components/forms/AsyncSelect/AsyncSelect.tsx
  packages/api-catalog-spa/src/context/RecentVisitContext/RecentVisitContext.tsx
  packages/api-catalog-spa/src/pages/APICUDPage/APICUDPage.tsx
  packages/api-catalog-spa/src/pages/APICUDPage/components/APIBasicDetailsForm/APIBasicDetailsForm.tsx
  packages/api-catalog-spa/src/pages/APICUDPage/components/APISchemaForm/APISchemaForm.tsx
  packages/api-catalog-spa/src/pages/APICUDPage/components/APISchemaForm/components/EnvironmentFormSection/EnvironmentFormSection.tsx
  packages/api-catalog-spa/src/pages/GQLPlaygroundToolboxPage/GQLPlaygroundToolboxPage.tsx
  packages/api-catalog-spa/src/pages/RedocToolboxPage/RedocToolboxPage.tsx
  packages/api-catalog-spa/src/pages/SwaggerToolboxPage/SwaggerToolboxPage.tsx
  packages/api-catalog-spa/src/utils/index.ts
  packages/api-catalog-spa/src/utils/loadThirdPartyScripts.ts
  packages/api-catalog-spa/src/vite-env.d.ts
Labels: bug

#1559 fix(api-catalog-service): updated mongoose validation to avoid require in schema field in db
  packages/api-catalog-service/package-lock.json
  packages/api-catalog-service/package.json
  packages/api-catalog-service/src/db/specSheet.ts
Labels: bug

#1557 feat(1883): lighthouse-service - added fields to be picked in total scoring
  packages/lighthouse-service/package-lock.json
  packages/lighthouse-service/package.json
  packages/lighthouse-service/src/audit-manager/typedef.graphql
  packages/lighthouse-service/src/lighthouse-db-manager/lighthouse-db-manager.ts
  packages/lighthouse-service/src/lighthouse-db-manager/types.ts
Labels: enhancement

#1560 feat(api-catalog-spa): hiding edit button if user is not owner or created by
  packages/api-catalog-spa/package-lock.json
  packages/api-catalog-spa/package.json
  packages/api-catalog-spa/src/pages/APICUDPage/components/APIReview/APIReview.tsx
  packages/api-catalog-spa/src/pages/APIDescriptionPage/APIDescriptionPage.tsx
  packages/api-catalog-spa/src/pages/APIDescriptionPage/components/DetailsSection/DetailsSection.tsx
  packages/api-catalog-spa/src/pages/APIDescriptionPage/hooks/useGetANamespaceBySlug.ts
  packages/api-catalog-spa/src/pages/APIDescriptionPage/hooks/useSubscribeSchema.tsx
  packages/api-catalog-spa/src/utils/hasUserApiEditAccess.ts
Labels: bug, enhancement

#1558 feat(1883): lighthouse-spa - implemented leaderboard score column customization
  packages/lighthouse-spa/package-lock.json
  packages/lighthouse-spa/package.json
  packages/lighthouse-spa/src/app/leaderboard/leaderboard.gql.ts
  packages/lighthouse-spa/src/app/leaderboard/leaderboard.service.ts
  packages/lighthouse-spa/src/app/leaderboard/pages/leaderboard/leaderboard.component.html
  packages/lighthouse-spa/src/app/leaderboard/pages/leaderboard/leaderboard.component.scss
  packages/lighthouse-spa/src/app/leaderboard/pages/leaderboard/leaderboard.component.ts
  packages/lighthouse-spa/src/app/leaderboard/pipes/leaderboard-label-formater.pipe.ts
  packages/lighthouse-spa/src/app/utils/leaderboardTable.ts
Labels: enhancement

#1562 fix(lh-spa): fixed undefined error in leaderboard column function in build timeline chart
  packages/lighthouse-spa/package-lock.json
  packages/lighthouse-spa/package.json
  packages/lighthouse-spa/src/app/utils/leaderboardTable.ts
Labels: bug

#1563 fix(api-catalog-spa): fixed schema desc showing namespace desc
  packages/api-catalog-spa/package-lock.json
  packages/api-catalog-spa/package.json
  packages/api-catalog-spa/src/pages/APIDescriptionPage/APIDescriptionPage.tsx
Labels: bug
