Repository 1-Platform/one-platform, pull requests merged in 2022-01, with the labels that each got.

#1363 fix(1362) - Change component catalog drupal svg
  packages/component-catalog-spa/src/assets/images/druplicon-vector.svg
Labels: bug, chore

#1360 feat(rproxy): Add keycloak middleware for SPAs
  packages/reverse-proxy-service/.env.example
  packages/reverse-proxy-service/README.md
  packages/reverse-proxy-service/package-lock.json
  packages/reverse-proxy-service/package.json
  packages/reverse-proxy-service/src/app.ts
  packages/reverse-proxy-service/src/config/env.ts
  packages/reverse-proxy-service/src/couchdb/resolver.ts
  packages/reverse-proxy-service/src/middleware/jwtAuth.ts
  packages/reverse-proxy-service/src/restricted-spas/index.ts
  packages/reverse-proxy-service/src/restricted-spas/resolver.ts
  packages/reverse-proxy-service/src/spec/restricted-spas.spec.ts
  packages/reverse-proxy-service/src/utils/keycloakAuth.ts
Labels: enhancement

#1361 (chore:1680) - Updated the test cases for the Search Microservice
  packages/search-service/package-lock.json
  packages/search-service/package.json
  packages/search-service/src/e2e/mock.js
  packages/search-service/src/e2e/mock.json
  packages/search-service/src/e2e/search.spec.ts
Labels: chore

#1365 fix: fixed early websocket closing and api changed to new menu-drawer
  packages/opc-base/package-lock.json
  packages/opc-base/package.json
  packages/opc-base/src/config/graphql.ts
  packages/opc-base/src/opc-provider/opc-provider.ts
Labels: bug

#1364 fix(1779) - search-spa fixed dropdown onblur closing
  packages/search-spa/src/app/search/search.component.html
  packages/search-spa/src/app/search/search.component.ts
Labels: bug

#1366 1577 - Updated the querys in the opc-base package
  packages/opc-base/package-lock.json
  packages/opc-base/package.json
  packages/opc-base/src/gql/opc-app-layout.ts
Labels: chore

#1232 Deepsource fix found warning comments in code
  .gitignore
  cli/generator-op-microservice/__tests__/app.js
  packages/documentation-spa/src/theme/Layout/index.jsx
Labels: stale

#1367 feat: updated all spa ssi to latest version
  packages/api-catalog-spa/package-lock.json
  packages/api-catalog-spa/package.json
  packages/api-catalog-spa/public/index.html
  packages/developer-console-spa/package-lock.json
  packages/developer-console-spa/package.json
  packages/developer-console-spa/public/index.html
  packages/documentation-spa/package-lock.json
  packages/documentation-spa/package.json
  packages/feedback-spa/package.json
  packages/feedback-spa/public/index.html
  packages/home-spa/package-lock.json
  packages/home-spa/package.json
  packages/home-spa/src/_includes/partials/header.njk
  packages/lighthouse-spa/package-lock.json
  packages/lighthouse-spa/package.json
  packages/search-spa/package-lock.json
  packages/search-spa/package.json
  packages/user-group-spa/package-lock.json
  packages/user-group-spa/package.json
  packages/user-group-spa/public/index.html
Labels: enhancement

#1370 Feat#1686: User-group service unit tests, covered users and user group tests
  packages/user-group-service/package-lock.json
  packages/user-group-service/package.json
  packages/user-group-service/src/e2e/mock.js
  packages/user-group-service/src/e2e/mock.json
  packages/user-group-service/src/e2e/rover.mock.js
  packages/user-group-service/src/e2e/user.spec.ts
Labels: chore

#1375 hotfix: react-script package-lock file build issue
  packages/api-catalog-spa/package-lock.json
  packages/api-catalog-spa/package.json
  packages/component-catalog-spa/package-lock.json
  packages/developer-console-spa/package-lock.json
Labels: bug

#1377 fix(rproxy): Create custom middleware for keycloak
  packages/reverse-proxy-service/.env.example
  packages/reverse-proxy-service/package-lock.json
  packages/reverse-proxy-service/package.json
  packages/reverse-proxy-service/src/app.ts
  packages/reverse-proxy-service/src/config/env.ts
  packages/reverse-proxy-service/src/middleware/keycloakAuth.ts
  packages/reverse-proxy-service/src/restricted-spas/index.ts
  packages/reverse-proxy-service/src/restricted-spas/resolver.ts
  packages/reverse-proxy-service/src/utils/keycloakAuth.ts
Labels: bug

#1373 feat(1577): updated dev console feedback page with server
  packages/developer-console-spa/package-lock.json
  packages/developer-console-spa/package.json
  packages/developer-console-spa/src/@types/Feedback/types.d.ts
  packages/developer-console-spa/src/components/ConfigureFeedback.tsx
  packages/developer-console-spa/src/hooks/useFeedbackConfig.ts
  packages/developer-console-spa/src/services/feedbackConfig.ts
  packages/developer-console-spa/src/utils/formErrorMsg.ts
  packages/developer-console-spa/src/utils/gql-queries/app-feedback-config.ts
  packages/developer-console-spa/src/utils/gql-queries/create-feedback-config.ts
  packages/developer-console-spa/src/utils/gql-queries/index.ts
  packages/developer-console-spa/src/utils/gql-queries/update-feedback-config.ts
Labels: enhancement

#1394 test(feedback,ideahub,lighthousetests):fix for failing tests of light…
  e2e/integration/feedbacktests.js
  e2e/integration/ideahubtests.js
  e2e/integration/lighthousetests.js
Labels: test-automation

#1395 test(ideahub): deleted innovation hub duplicate test file
  e2e/integration/innovationhubtests.js
Labels: test-automation

#1398 feat: feedback service - added filters for feedback listing and impro…
  packages/feedback-service/package-lock.json
  packages/feedback-service/package.json
  packages/feedback-service/src/e2e/feedback.spec.ts
  packages/feedback-service/src/feedbacks/helpers.ts
  packages/feedback-service/src/feedbacks/resolver.ts
  packages/feedback-service/src/feedbacks/schema.ts
  packages/feedback-service/src/feedbacks/typedef.graphql
  packages/feedback-service/src/types.d.ts
Labels: enhancement

#1397 feat(1307): dev-console - implemented feedback list page
  packages/developer-console-spa/package-lock.json
  packages/developer-console-spa/package.json
  packages/developer-console-spa/src/@types/Feedback/types.d.ts
  packages/developer-console-spa/src/App.tsx
  packages/developer-console-spa/src/components/feedback/ConfigureFeedback.tsx
  packages/developer-console-spa/src/components/feedback/FeedbackList.tsx
  packages/developer-console-spa/src/hooks/useDebounce.tsx
  packages/developer-console-spa/src/hooks/usePagination.tsx
  packages/developer-console-spa/src/hooks/useToggle.ts
  packages/developer-console-spa/src/services/feedback.ts
  packages/developer-console-spa/src/utils/gql-queries/get-app-feedbacks.ts
  packages/developer-console-spa/src/utils/gql-queries/index.ts
Labels: enhancement

#1412 test(lighthouse):fix for the failing tests of lighthouse
  e2e/integration/ideahubtests.js
  e2e/integration/lighthousetests.js
Labels: test-automation

#1423 Fix: Typo in Pull Request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#1421 hotfix: feedback-service module null fixed
  packages/feedback-service/package-lock.json
  packages/feedback-service/package.json
  packages/feedback-service/src/feedbacks/helpers.ts
Labels: bug

#1429 hotfix: feedback spa fixed pf import issue in build
  packages/feedback-spa/index.html
  packages/feedback-spa/package-lock.json
  packages/feedback-spa/package.json
  packages/feedback-spa/src/main.tsx
  packages/feedback-spa/src/pages/HomePage/HomePage.tsx
Labels: bug
