Repository 1-Platform/one-platform, pull requests merged in 2023-01, with the labels that each got.

#1690 fix(2364, 2368, 2363): resolved api-catalog-spa minor bugs and typos
  packages/api-catalog-spa/package-lock.json
  packages/api-catalog-spa/package.json
  packages/api-catalog-spa/src/pages/APICUDPage/APICUDPage.helpers.ts
  packages/api-catalog-spa/src/pages/APICUDPage/APICUDPage.tsx
  packages/api-catalog-spa/src/pages/APICUDPage/APICUDPage.types.ts
  packages/api-catalog-spa/src/pages/APICUDPage/components/APIBasicDetailsForm/APIBasicDetailsForm.tsx
  packages/api-catalog-spa/src/pages/APICUDPage/components/APISchemaForm/APISchemaForm.tsx
Labels: bug

#1689 Implemented Ownership transfer functionality in Developer Console
  packages/developer-console-spa/src/common/services/project.ts
  packages/developer-console-spa/src/common/utils/gql-queries/index.ts
  packages/developer-console-spa/src/common/utils/gql-queries/transfer-project-ownership.ts
  packages/developer-console-spa/src/pages/Home/index.tsx
  packages/developer-console-spa/src/pages/ProjectConsoleShell/index.tsx
  packages/developer-console-spa/src/pages/ProjectSettings/General.tsx
  packages/developer-console-spa/src/pages/ProjectSettings/Permissions.tsx
  packages/developer-console-spa/src/pages/ProjectSettings/components/AddMemberForm.tsx
  packages/developer-console-spa/src/pages/ProjectSettings/components/TransferOwnershipForm.tsx
Labels: bug, enhancement

#1694 2163 - Included API Catalog configuration to the API Gateway
  packages/api-gateway-service/config.json
  packages/api-gateway-service/package-lock.json
  packages/api-gateway-service/package.json
Labels: chore

#1691 2163 - Integrated API Catalog with Search
  packages/api-catalog-service/package-lock.json
  packages/api-catalog-service/package.json
  packages/api-catalog-service/src/graph/namespace/resolver.ts
  packages/api-catalog-service/src/graph/namespace/updateSearch.ts
Labels: enhancement

#1696 feat(rproxy): setup a permanent redirect for an app and updated Dockerfile
  packages/reverse-proxy-service/Dockerfile
  packages/reverse-proxy-service/package-lock.json
  packages/reverse-proxy-service/src/restricted-spas/index.ts
  packages/reverse-proxy-service/src/setup/database.ts
Labels: enhancement, chore

#1697 fix(rproxy): change token type in forwarded header
  packages/reverse-proxy-service/package-lock.json
  packages/reverse-proxy-service/package.json
  packages/reverse-proxy-service/src/restricted-spas/resolver.ts
  packages/reverse-proxy-service/src/server.ts
  packages/reverse-proxy-service/src/utils/applicationCache.ts
Labels: bug, regression

#1698 feat(2448): Added deeplink to swagger
  packages/api-catalog-spa/package-lock.json
  packages/api-catalog-spa/package.json
  packages/api-catalog-spa/src/pages/SwaggerToolboxPage/SwaggerToolboxPage.tsx
Labels: enhancement

#1703 (feat: 2381) - Included Matomo Tracking for One Platform SPAs
  packages/developer-console-spa/.env.example
  packages/developer-console-spa/package-lock.json
  packages/developer-console-spa/package.json
  packages/developer-console-spa/public/index.html
  packages/feedback-spa/.env.example
  packages/feedback-spa/package-lock.json
  packages/feedback-spa/package.json
  packages/feedback-spa/src/App.tsx
  packages/home-spa/.env.example
  packages/home-spa/package-lock.json
  packages/home-spa/package.json
  packages/home-spa/src/_data/env.js
  packages/home-spa/src/_includes/layout/base.njk
  packages/lighthouse-spa/package-lock.json
  packages/lighthouse-spa/package.json
  packages/lighthouse-spa/set-env.ts
  packages/lighthouse-spa/src/app/app.module.ts
  packages/lighthouse-spa/src/environments/environment.prod.ts
  packages/lighthouse-spa/src/environments/environment.ts
  packages/search-spa/package-lock.json
  packages/search-spa/package.json
  packages/search-spa/set-env.ts
  packages/search-spa/src/app/app.component.ts
  packages/search-spa/src/app/app.module.ts
  packages/search-spa/src/environments/environment.prod.ts
  packages/search-spa/src/environments/environment.ts
Labels: enhancement

#1700 feedback(service) - Update feedback service config map
  packages/feedback-service/package-lock.json
  packages/feedback-service/package.json
  packages/feedback-service/src/e2e/mock.js
  packages/feedback-service/src/feedback-config/resolver.ts
  packages/feedback-service/src/feedback-config/schema.ts
  packages/feedback-service/src/feedback-config/typedef.graphql
  packages/feedback-service/src/feedbacks/helpers.ts
  packages/feedback-service/src/feedbacks/resolver.ts
  packages/feedback-service/src/feedbacks/schema.ts
  packages/feedback-service/src/feedbacks/typedef.graphql
  packages/feedback-service/src/types.d.ts
Labels: chore, work-in-progress
