Repository 1-Platform/one-platform, pull requests merged in 2023-02, with the labels that each got.

#1705 fix(apps): appdrawerentry app query fix
  docker-compose.yml
  packages/apps-service/package-lock.json
  packages/apps-service/src/__tests__/app-drawer-entrys-queries.gql.ts
  packages/apps-service/src/__tests__/app-drawer-entrys.spec.ts
  packages/apps-service/src/__tests__/projects-queries.gql.ts
  packages/apps-service/src/__tests__/projects.spec.ts
  packages/apps-service/src/modules/application-drawer-entry/resolver.ts
  packages/apps-service/src/modules/application-drawer-entry/schema.gql.ts
Labels: bug, enhancement

#1709 feat(2392): updated feedback submission with new project id support
  packages/opc-base/dev/config.es.example.js
  packages/opc-base/dev/config.example.js
  packages/opc-base/docs/opc-base.md
  packages/opc-base/package-lock.json
  packages/opc-base/package.json
  packages/opc-base/src/gql/types.ts
  packages/opc-base/src/opc-base/opc-base.test.ts
  packages/opc-base/src/opc-base/types.ts
  packages/opc-base/src/opc-provider/opc-provider.ts
Labels: enhancement

#1712 chore(doc-spa): Updating SPA deployment guide
  packages/doc-spa/docs/deployment-guidelines/spa-deployment-guideline.md
  packages/doc-spa/docs/deployment-guidelines/spa-deployment-guidelines.md
  packages/doc-spa/package-lock.json
  packages/doc-spa/package.json
  packages/doc-spa/sidebars.js
Labels: documentation
